@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

'left to right direction

class CreateJobUI {
}

class CreateJobController {
    +createJob(title : String) : void
    +getInstance() : JobRepository
}

class Repositories {
    +getJobRepository() : JobRepository
}

class JobRepository {
    +createJob(title : String) : Job
    +checkForDuplicates() : void
}

class Job {
    - title : String
    + Job(title : String)
    +verifyFilled(job : Job) : void
    +verifySpecialCharacters(job : Job) : void
}

CreateJobUI ..> CreateJobController
Repositories --> "1" JobRepository : jobRepository
Repositories --> Repositories : instance
JobRepository --> "*" Job : jobs
CreateJobController ..> Repositories : repositories
CreateJobController ..> JobRepository : jobRepository

@enduml
