@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as Employee
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant "jobRepository:\nJobRepository" as jobRepository

activate Employee

Employee -> UI : wants to create a new job
activate UI

UI -> CTRL** : create

UI --> Employee : asks for the info needed (title)

Employee -> UI : provides job title

UI --> Employee : shows a verification dialog

Employee -> UI : confirms job creation

UI -> CTRL : createJob(title)
deactivate UI
activate CTRL
        ref over CTRL
            Get Job Repository
        end ref

CTRL -> jobRepository : createJob(title)
deactivate CTRL
activate jobRepository

        ref over jobRepository
            Create Job
        end ref

    activate jobRepository
    jobRepository -> jobRepository : check for duplicates
    activate jobRepository
    jobRepository --> jobRepository
    deactivate jobRepository

jobRepository --> CTRL : job
deactivate jobRepository
activate CTRL
deactivate jobRepository

CTRL --> UI : success
deactivate CTRL
activate UI
UI --> Employee : displays operation success

deactivate UI
deactivate Employee

@enduml