@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as Employee
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\nJobRepository" as jobRepository
participant ":Job" as Job

activate Employee
Employee -> UI : wants to create a new job
activate UI
UI -> CTRL** : create
UI --> Employee : asks for the info needed (title and description)
Employee -> UI : provides job title and description
UI --> Employee : shows a verification dialog
Employee -> UI : confirms job creation


UI -> CTRL : createJob(title, description)
deactivate UI
activate CTRL
CTRL -> GlobRepo : getInstance()
activate GlobRepo
GlobRepo --> CTRL : repositories
deactivate GlobRepo

CTRL -> PLAT : getJobRepository()
activate PLAT
PLAT -->  CTRL: jobRepository
deactivate PLAT

CTRL -> jobRepository : createJob(title, description)
activate jobRepository

    jobRepository -> Job** : create(title, description)
        activate Job

    Job -> Job : verifyFilled(job)
        activate Job
        Job -> Job : verifySpecialCharacters(job)
        activate Job
        Job --> Job
        deactivate Job
    Job --> Job
    deactivate Job
    'Job -> Job : addJob(job)
    Job --> jobRepository : job
    deactivate Job
    jobRepository -> jobRepository : check for duplicates
    activate jobRepository
    jobRepository --> jobRepository
    deactivate jobRepository
    deactivate Job
jobRepository --> CTRL : job
deactivate jobRepository
deactivate jobRepository

CTRL --> UI : success
deactivate CTRL
activate UI
UI --> Employee : displays operation success

deactivate UI
deactivate Employee

@enduml
