@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "FM" as FM
participant ":System" as System

activate FM

    FM -> System : requests to register a vehicle
    activate System
loop
        System --> FM : requests vehicle data (VIN, Vehicle Platte, Tare Weight, Gross Weight, Current Km, Acquisition Date, Maintenance Frequency)
    deactivate System

    FM -> System : types vehicle data
    activate System

        System --> FM : validates VIN (unique and not existing) and requests more data
    deactivate System

    FM -> System : selects vehicle data (Brand, Model)
        activate System

        System --> FM : shows all data and requests confirmation
    deactivate System
end
    FM -> System : confirms data
    activate System

        System --> FM :  shows vehicle registration information
    deactivate System

@enduml