@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "FM" as FM
participant ":System" as System

activate FM

    FM -> System : requests to register a vehicle
    activate System

        System --> FM : requests vehicle data (VIN, Tare Weight, Gross Weight, Current Km, Acquisition Date, Maintenance Frequency)
    deactivate System

    FM -> System : types vehicle data
    activate System

        System --> FM : validates VIN (unique and not existing) and requests more data (Brand, Model, Type)
    deactivate System

    FM -> System : selects vehicle data
        activate System

        System --> FM : shows all data and requests confirmation
    deactivate System

    FM -> System : confirms data
    activate System

        System --> FM :  vehicle registration information
        System --> FM : stores vehicle registration information
    deactivate System

@enduml