@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as ADM
participant ":CreateTeamUI" as UI
participant ":CreateTeamController" as CTRL
participant "TeamRepository:\nTeamRepository" as TeamRepository

activate ADM

    ADM -> UI : asks to create a new team
    activate UI

                UI -> CTRL** : create
                deactivate UI
                activate CTRL

                    ref over CTRL
                                Get Skills List

                            end ref

                    CTRL --> UI : skillsList
                deactivate CTRL
                activate UI

                UI --> ADM : shows skills list and asks to select one
                deactivate UI

        ADM --> UI : selects skills
        activate UI

        UI --> ADM : requests data (maximum team size)
        deactivate UI

    ADM -> UI : types requested data
    activate UI

        UI --> ADM : shows data and requests for confirmation
        deactivate UI

    ADM -> UI : confirms data
    activate UI

    UI --> ADM: show the proposal
        deactivate UI

        ADM -> UI: use accepts
        activate UI

        UI -> CTRL : create Team
        deactivate UI
        activate CTRL

            |||
                CTRL -> TeamRepository: createTeam(skills, minTeamSize, maxTeamSize)
                deactivate CTRL
                activate TeamRepository

                ref over TeamRepository

                            Create Team

                        end ref

            TeamRepository --> CTRL: team
            deactivate TeamRepository
            activate CTRL

            CTRL --> UI : success
            deactivate CTRL
            activate UI
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml