@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as ADM
participant ":CreateTeamUI" as UI
participant ":CreateTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "SkillRepository:\nSkillRepository" as SkillRepository
participant "TeamRepository:\nTeamRepository" as TeamRepository
participant "team\n:Team" as Team

activate ADM

    ADM -> UI : asks to create a new team
    activate UI

                UI -> CTRL** : create
                deactivate UI
                activate CTRL

                    CTRL -> CTRL : getSkills()
                    activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getSkillRepository()
                    activate PLAT

                        PLAT --> CTRL: skillRepository
                    deactivate PLAT

                    CTRL -> SkillRepository : getSkills()
                    activate SkillRepository

                        SkillRepository --> CTRL : skillsList
                    deactivate SkillRepository

                    CTRL --> CTRL
                    deactivate CTRL

                    CTRL --> UI : skillsList
                                        deactivate CTRL

                    activate UI

                UI --> ADM : shows skills list and asks to select one

        ADM -> UI : selects skills

        UI --> ADM : requests maximum team size

    ADM -> UI : types requested data (maximum&minimum  team size)

        UI --> ADM : shows data and asks for verification

    ADM -> UI : submits data

        UI -> CTRL : createTeam(skills, maxTeamSize)
        deactivate UI
        activate CTRL

            CTRL -> CTRL : getSkillByDescription(skillDescription)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillRepository()
                activate PLAT

                    PLAT --> CTRL : SkillRepository
                deactivate PLAT

                CTRL -> SkillRepository : getSkillByDescription(skillDescription)
                activate SkillRepository

                    SkillRepository --> CTRL : skill
                deactivate SkillRepository
                    CTRL --> CTRL : skill
            deactivate CTRL


            |||
                CTRL -> TeamRepository: createTeam(skills, maxTeamSize)
                deactivate CTRL
                activate TeamRepository

                TeamRepository -> Team**: addTeam (team)

                    TeamRepository -> TeamRepository: addTeam(team)
                    activate TeamRepository
                        TeamRepository -> TeamRepository: validateTeam(team)
                        activate TeamRepository
                            TeamRepository --> TeamRepository
                            deactivate TeamRepository

                    TeamRepository --> TeamRepository
                deactivate TeamRepository

            TeamRepository --> CTRL: team
            deactivate TeamRepository
            activate CTRL


            CTRL --> UI : success
            deactivate CTRL
            activate UI

            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml