@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as SkillRepository

autonumber 3

 -> CTRL : getSkillsList()
activate CTRL
    group Get Skills List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getSkillRepository()
            activate PLAT

                PLAT --> CTRL: skillRepository
            deactivate PLAT

            CTRL -> SkillRepository : getSkills()
            activate SkillRepository

                SkillRepository --> CTRL : skillList
            deactivate SkillRepository


    end
    autonumber 4
    <-- CTRL  : SkillsList
deactivate CTRL


@enduml