@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nskillRepository" as SkillRepository

autonumber 12
-> CTRL : getSkillByDescription(skillDescription)


activate CTRL
    group Get Skill
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getSkillRepository()
        activate PLAT

            PLAT -> CTRL : SkillRepository
        deactivate PLAT

        CTRL -> SkillRepository : getSkillByDescription(skillDescription)
        activate SkillRepository

            SkillRepository --> CTRL : skill
        deactivate SkillRepository

    end group

    autonumber 13
    <-- CTRL : skill

deactivate CTRL


@enduml