@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "TeamRepository:\nTeamRepository" as TeamRepository

autonumber 32
-> TeamRepository: createTeam(List<Collaborator>, List<Skill>, minTeamSize, maxTeamSize)

activate TeamRepository
    group Create Team
            activate TeamRepository

            TeamRepository -> Team**: createTeam(List<Collaborator>, List<Skill>, minTeamSize, maxTeamSize)

                TeamRepository -> TeamRepository: validateTeam(team)
            activate TeamRepository

                TeamRepository --> TeamRepository
            deactivate TeamRepository

            TeamRepository -> TeamRepository: addTeam(team)


        deactivate TeamRepository

    end

    <-- TeamRepository : team
deactivate TeamRepository


@enduml
