@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTeamController" as CTRL

autonumber 16
-> CTRL: createTeam(skills, maxTeamSize )

autonumber 16.1
activate CTRL
    group Create Team

        CTRL -> TeamRepository: createTeam(skills, maxTeamSize)
                        activate TeamRepository

                        TeamRepository -> Team**: createTeam (skills, maxTeamSize)

                            TeamRepository -> TeamRepository: addTeam(team)
                            activate TeamRepository
                                TeamRepository -> TeamRepository: validateTeam()
                                activate TeamRepository
                                    TeamRepository --> TeamRepository
                                    deactivate TeamRepository

                            TeamRepository --> TeamRepository
                        deactivate TeamRepository

                    TeamRepository --> CTRL: team
                    deactivate TeamRepository
    end

    autonumber 17
    <-- CTRL : success
deactivate CTRL


@enduml