@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "TeamRepository:\nTeamRepository" as TeamRepository

autonumber 16
-> TeamRepository: createTeam(skills, minTeamSize, maxTeamSize )

activate TeamRepository
    group Create Team

                        activate TeamRepository

                        TeamRepository -> Team**: createTeam (skills, maxTeamSize)

                                TeamRepository -> TeamRepository: validateTeam()
                                activate TeamRepository
                                    TeamRepository --> TeamRepository
                                    deactivate TeamRepository

                            TeamRepository -> TeamRepository: addTeam(team)


                    deactivate TeamRepository
    end

    autonumber 17
    <-- TeamRepository : team
deactivate TeamRepository


@enduml