@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US014

autonumber

actor "QAM" as QAM
participant ":System" as System

activate QAM

    QAM -> System : asks to run the tests
    activate System

    QAM -> System : shows test results
    activate System

        System --> QAM : displays operation success
    deactivate System

@enduml