@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US008

autonumber

actor "Facilities Manager" as FM
participant ":System" as System

activate FM

    FM -> System : requests to list vehicles needing check-up
    activate System

        System --> FM : retrieves vehicles' data (e.g., current kilometers, maintenance/checkup frequency)
    deactivate System

    FM -> System : provides required data
    activate System

        System --> FM : generates list of vehicles needing check-up
    deactivate System

@enduml