@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class Collaborator {
    name
    birthdate
    admissionDate
    mobileNumber
    e-mail
    taxpayerNumber
}

class AgendaEntry {
    startingDate
    progressStatus

}


class ToDoEntry {
    title
    description
    duration
    urgencyStatus


}

class Document{
    documentType
    identificationNumber
}

class Address{
    street
    zipCode
    city
}


class Agenda{
}





Agenda "1" -- "1..*" AgendaEntry: has >

AgendaEntry "1" -- "1" ToDoEntry: is >

Collaborator "1..*" -- "*" AgendaEntry : record conclusion >

Collaborator "1" -- "1..*" Document : has >

Collaborator "1..*" -- "1" Address : has a >

@enduml
