@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class Collaborator {
    name
    birthdate
    admissionDate
    mobileNumber
    e-mail
    taxpayerNumber
}

class Entry {
    urgencyStatus
    estimatedDate
    progressStatus

}

class Document{
    documentType
    identificationNumber
}

class Address{
    street
    zipCode
    city
}

class Task {
    title
    description

}

class Agenda{
}

class ToDoList{
}



Agenda "1" -- "1..*" Entry: has >

ToDoList "1" -- "1..*" Entry : has >

Entry "1" -- "1" Task: is >

Collaborator "1..*" -- "*" Entry : record conclusion >

Collaborator "1" -- "1..*" Document : has >

Collaborator "1..*" -- "1" Address : has a >

@enduml
