@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 12

'hide footbox
participant ":CreateJobController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT

group Get Job Repository
activate CTRL
CTRL -> GlobRepo : getInstance()
activate GlobRepo
GlobRepo --> CTRL : repositories
deactivate GlobRepo

CTRL -> PLAT : getJobRepository()
activate PLAT
PLAT -->  CTRL: jobRepository
deactivate PLAT


end
CTRL ->  : createJob(title)
deactivate CTRL

@enduml

