@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as Employee
participant ":CreateJobUI" as UI
participant ":CreateJobController" as CTRL
participant "jobRepository:\nJobRepository" as jobRepository
participant ":Job" as Job
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT

activate Employee

Employee -> UI : asks to create a new job
activate UI

UI -> CTRL** : create

UI --> Employee : requests data (job title)
deactivate UI

Employee -> UI : types requested data
activate UI

UI --> Employee : shows data (job title) and requests confirmation
deactivate UI

Employee -> UI : confirms data
activate UI

UI -> CTRL : createJob(title)
deactivate UI
activate CTRL
        ref over CTRL
            Get Job Repository
        end ref

CTRL -> jobRepository : createJob(title)
deactivate CTRL
activate jobRepository

        ref over jobRepository
            Create Job
        end ref

    deactivate jobRepository

jobRepository --> CTRL : job
deactivate jobRepository
activate CTRL
deactivate jobRepository

CTRL --> UI : success
deactivate CTRL
activate UI
UI --> Employee : displays success message (job created successfully)

deactivate UI
deactivate Employee

@enduml