@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "VFM" as VFM
participant ":System" as System

activate VFM

    VFM -> System : requests to register a vehicle
    activate System

        System --> VFM : requests vehicle data (VIN, Vehicle Platte, Tare Weight, Gross Weight,\n Current Km, Acquisition Date, Maintenance Frequency)
    deactivate System

    VFM -> System : types vehicle data
    activate System

        System --> VFM : validates VIN (unique and not existing) and requests more data
    deactivate System

    VFM -> System : selects vehicle data (Brand, Model)
        activate System

        System --> VFM : shows all data and requests confirmation
    deactivate System

    VFM -> System : confirms data
    activate System

        System --> VFM :  shows vehicle registration information
    deactivate System

@enduml