@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "VFM" as VFM
participant ":System" as System

activate VFM

    VFM -> System : requests to register a vehicle
    activate System

        System --> VFM : requests vehicle data (VIN, Vehicle Plate, Tare Weight, Gross Weight,\n Current Km, Acquisition Date, Maintenance Frequency, Brand, Model, Type)
    deactivate System

    VFM -> System : types and selects vehicle data

    activate System

        System --> VFM : shows all data and requests confirmation
    deactivate System

    VFM -> System : confirms data
    activate System

        System --> VFM :  shows vehicle registration information
    deactivate System

@enduml