@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam line type polyline

package CreateMaintenanceReportSystem {
class ListMaintenanceUI{
}

class ListMaintenanceController {
    - vehicleRepository: VehicleRepository
    - maintenanceRepository: MaintenanceRepository

    + createMaintenanceReport(vehiclesList: List<Vehicle>): MaintenanceReport
}

class Repositories {
    - instance: Repositories
    - vehicleRepository: VehicleRepository
    - maintenanceRepository: MaintenanceRepository

    + getInstance(): Repositories
    + getVehicleRepository(): VehicleRepository
    + getMaintenanceRepository(): MaintenanceRepository
}

class VehicleRepository {
    - vehicleList: List<vehicle>

}

class MaintenanceRepository {
    - maintenanceReport: MaintenanceReport

    + getVehiclesNeedingMaintenance(vehicleList: List<Vehicle>): List<Vehicle>
    + createMaintenanceReport(vehiclesList: List<Vehicle>): MaintenanceReport
}

class Vehicle {
     - VIN: String
     - brand: String
     - model: String
     - type: String
     - vehiclePlate: String
     - tareWeight: double
     - grossWeight: double
     - currentKm: double
     - acquisitionDate: Date
     - maintenanceFrequency: int

    + Vehicle(VIN: String,brand: String, model: String, type: String, vehiclePlate: String, tareWeight: double, \ngrossWeight: double, currentKm: double, acquisitionDate: Date, maintenanceFrequency: int)
}



class MaintenanceReport {
    - data: String
    - vehicleList: List<vehicle>

    + MaintenanceReport(data: String, vehicleList: List<vehicleList>

}

ListMaintenanceUI --> ListMaintenanceController: Submit request
ListMaintenanceController --> Repositories: Get
ListMaintenanceController --> MaintenanceRepository: Create Maintenance Report
Repositories --> VehicleRepository: Get
Repositories --> MaintenanceRepository: Get
VehicleRepository --> Vehicle: Has
MaintenanceRepository --> Vehicle: Get
MaintenanceRepository --> MaintenanceReport: Create
}
@enduml
