@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "maintenanceRepository:\nMaintenanceRepository" as MaintenanceRepository
participant "maintenanceReport\n:MaintenanceReport" as MaintenanceReport

autonumber 11
-> MaintenanceRepository : createMaintenanceReport(vehiclesList)
activate MaintenanceRepository

    group Create Maintenance Report

        MaintenanceRepository -> MaintenanceRepository: getVehiclesNeedingMaintenance(vehicleList)

        MaintenanceRepository -> MaintenanceReport **: createMaintenanceReport(vehiclesList)
        deactivate MaintenanceRepository
        activate MaintenanceReport

        MaintenanceReport --> MaintenanceRepository : maintenance Report
        deactivate MaintenanceReport

        activate MaintenanceRepository
    end group

    autonumber 13
    <-- MaintenanceRepository : maintenanceReport

deactivate MaintenanceRepository


@enduml