@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ListMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "maintenanceRepository:\nMaintenanceRepository" as MaintenanceRepository
participant "maintenanceReport\n:MaintenanceReport" as MaintenanceReport

autonumber 11
-> CTRL : createMaintenanceReport(vehiclesList)

activate CTRL
    group Create Maintenance Report

        CTRL -> CTRL : createMaintenanceReport(vehiclesList)
                    activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                        activate RepositorySingleton

                            RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                        CTRL -> PLAT : getMaintenanceRepository()
                        activate PLAT

                            PLAT --> CTRL: MaintenanceRepository
                        deactivate PLAT

                        CTRL -> MaintenanceRepository : createMaintenanceReport(vehiclesList)
                        activate MaintenanceRepository

                            MaintenanceRepository -> MaintenanceReport : createMaintenanceReport(vehiclesList)
                            activate MaintenanceReport

                            MaintenanceReport --> MaintenanceRepository : maintenanceReport
                            deactivate MaintenanceReport

                        MaintenanceRepository --> CTRL : maintenanceReport
                        deactivate MaintenanceRepository

                    CTRL --> CTRL : maintenanceReport
                    deactivate CTRL

    end group

    autonumber 13
    <-- CTRL : taskCategory

deactivate CTRL


@enduml