@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":ListMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

autonumber 3

 -> CTRL : getVehiclesList()
activate CTRL
    group Get Vehicle List


            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getVehicleRepository()
            activate PLAT

            PLAT --> CTRL: VehicleRepository
            deactivate PLAT

            CTRL -> VehicleRepository : getVehiclesList()
            activate VehicleRepository

            VehicleRepository --> CTRL : vehiclesList
            deactivate VehicleRepository

    end

    autonumber 4
    <-- CTRL  : vehicleList
deactivate CTRL


@enduml