@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":ListMaintenanceUI" as UI
participant ":ListMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "maintenanceReport\n:MaintenanceReport" as MaintenanceReport

activate VFM

    VFM -> UI : requests to list vehicles needing maintenance
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getVehicleList()
        activate CTRL

        ref over CTRL
                                        Get Vehicle List

                                    end ref



            CTRL --> UI : vehicleList
        deactivate CTRL


        UI -> CTRL : generateMaintenanceReport(vehiclesList)
        activate CTRL

            CTRL -> CTRL : createMaintenanceReport(vehiclesList)
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: VehicleRepository
                deactivate PLAT

                CTRL -> VehicleRepository : createMaintenanceReport(vehiclesList)
                activate VehicleRepository

                ref over VehicleRepository
                                                Create maintenance Report

                                            end ref



                VehicleRepository --> CTRL : maintenanceReport
                deactivate VehicleRepository

            CTRL --> CTRL : maintenanceReport
            deactivate CTRL

            CTRL --> UI : maintenanceReport
        deactivate CTRL

        UI --> VFM : shows maintenance report
    deactivate UI

deactivate VFM

@enduml
