@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":ListMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

autonumber 3

 -> CTRL : get Vehicles List
activate CTRL
    group Get Vehicle List

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getMaintenanceRepository()
        activate PLAT

        PLAT --> CTRL: MaintenanceRepository
        deactivate PLAT

    end

    autonumber 4
deactivate CTRL


@enduml