@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":RouteUI" as UI
participant ":RouteController" as CTR
participant ":Route" as Repository

activate GSM

GSM -> UI : requests to import a .csv file
activate UI

UI -> CTR : creates
activate CTR

CTR -> Repository : importRoutes(filePath)
activate Repository


    ref over Repository
                        Import Routes from .csv File

                    end
Repository --> CTR: routes
deactivate Repository

CTR --> UI : displayConfirmation(success)
deactivate CTR

UI --> GSM : displays confirmation message
deactivate UI

@enduml
