@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto

skinparam classAttributeIconSize 0

class Route {
    - startPoint: WaterPoint
    - endPoint: WaterPoint
    - cost: double

    + getCost(): double
    + getStartPoint(): WaterPoint
    + getEndPoint(): WaterPoint
    + Route(startPoint: WaterPoint, endPoint: WaterPoint, cost: double)
}

class WaterPoint {
    - ID: String

    + getID(): String
    + WaterPoint(nome: String)
}

class RoutePointsReader {
    + importRoutesFromCSV(filePath: String): List<Route>
}

class Main {
    - unidade: String
    - caminho: String

    + writeGraph(routes: List<Route>): void
    + executarDOT(nomeArquivo: String): void
}

RoutePointsReader ..> Route : creates
Main --> "1" RoutePointsReader : uses
Main --> "1" Route : uses

@enduml