@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM\n(Green Space Manager)" as GSM
participant ":System" as System

activate GSM

    GSM -> System : requests statistical analysis of water consumption costs
    activate System

        System --> GSM : requests input data (e.g., time period, park identification)
    deactivate System

    GSM -> System : provides input data
    activate System

        System --> GSM : validates input data and initiates analysis process
    deactivate System

    GSM -> System : receives analysis results
    activate System

        System --> GSM : presents analysis outcomes (e.g., bar plot, average costs, statistical indicators)
    deactivate System

@enduml