@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US009

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : requests statistical analysis of water consumption costs
    activate System

        System --> GSM : requests input data (e.g., time period, park identification)
    deactivate System

    GSM -> System : provides input data
    activate System

        System --> GSM : validates input data and gives the outcome (e.g., bar plot,\n average costs, statistical indicators)
    deactivate System

@enduml