@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US002

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new job
    activate System

        System --> Employee : requests data (job title and job description)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : requests skills for the job (references existing skills more option "add new skill")

    Employee -> System : select to create a new skill
    activate System

     System --> Employee : forwards HRM to US001 sequence in order to register a new skill
          deactivate System

System --> Employee : requests skills for the job (references existing skills more option "add new skill")

    Employee -> System : selects a skill
    activate System

        System --> Employee : shows all data (title, description, and skills) and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays success message (job creation successful) and saves the job description linking it to the required skills
    deactivate System

@enduml