@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":CreateSkillUI" as UI
participant ":CreateSkillController" as CTRL
participant ":skillRepository" as skillRepository
participant ":Skill" as Skill

activate HRM

HRM ->UI : asks to create a skill
activate UI

UI -> CTRL** : create
activate CTRL

CTRL -> skillRepository : createSkill(designation)
activate skillRepository

    skillRepository -> Skill** : create(designation)
    deactivate skillRepository

        activate Skill

    Skill -> Skill : verifyFilled(skill)
        activate Skill
        Skill -> Skill : verifySpecialCharacters(skill)
    deactivate Skill

    Skill --> skillRepository : skill
     deactivate Skill
    activate skillRepository

    skillRepository -> skillRepository : check for duplicates
    deactivate Skill

    CTRL <-- skillRepository : skill
    deactivate CTRL

    CTRL --> UI : skill

    deactivate UI

    UI --> HRM : Displays successful or unsuccessful operation

deactivate HRM
@enduml
