@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as Employee
participant ":CreateSkillUI" as UI
participant ":CreateSkillController" as CTRL
participant "skillRepository:\nJobRepository" as skillRepository
participant ":Skill" as Skill

activate Employee
Employee -> UI : wants to create a new skill
activate UI

UI -> CTRL** : create
CTRL -> UI: requests (designation)
UI -> Employee : requests (designation)
Employee -> UI: designation
UI -> CTRL : createSkill(designation)
deactivate UI
activate CTRL

CTRL -> skillRepository : createSkill(designation)
deactivate CTRL
activate skillRepository

    skillRepository -> Skill** : create(designation)
    deactivate skillRepository

        activate Skill

    Skill -> Skill : verifyFilled(skill)
        activate Skill
        Skill -> Skill : verifySpecialCharacters(skill)
    deactivate Skill

    Skill --> skillRepository : skill
     deactivate Skill
    activate skillRepository

    skillRepository -> skillRepository : check for duplicates
    deactivate Skill
skillRepository --> CTRL : skill
deactivate skillRepository
activate CTRL
deactivate skillRepository

CTRL --> UI : success
deactivate CTRL
activate UI
UI --> Employee : displays operation success

deactivate UI
deactivate Employee

@enduml
