@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":CreateSkillUI" as UI
participant ":CreateSkillController" as CTRL
participant ":skillRepository" as skillRepository

activate HRM

HRM ->UI : asks to create a skill
activate UI

UI -> CTRL** : create
activate CTRL

CTRL -> skillRepository : createSkill(designation)
activate skillRepository

     ref over skillRepository
                Create a skill

            end ref
    activate skillRepository

    skillRepository -> skillRepository : check for duplicates

    CTRL <-- skillRepository : skill
    deactivate CTRL

    CTRL --> UI : skill

    deactivate UI

    UI --> HRM : Displays successful or unsuccessful operation

deactivate HRM
@enduml
