@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Domain Model - US022

left to right direction

skinparam classAttributeIconSize 0
hide circle
hide methods

class Agenda {

}

class Task {
    title
    description
    progressStatus
    urgencyStatus
    estimatedDate
}

class GreenSpace{
    designation
    area
    size
}


Agenda "1" -- "1..*" Task : has >

Task "*" -- "1" GreenSpace: associated to >

@enduml
