@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US007

autonumber

actor "VFM" as VFM
participant ":System" as System

activate VFM

    VFM -> System : asks to register a vehicle check-up
        activate System

    System --> VFM : asks vehicle to check-up
        deactivate System
    VFM -> System : select  vehicle
    activate System

    System --> VFM : requests data (vehicle identification, date)
    deactivate System

    VFM -> System : types requested data
    activate System

        System --> VFM : shows all data and requests confirmation
    deactivate System

    VFM -> System : confirms data
    activate System

        System --> VFM : displays operation success
    deactivate System

@enduml