@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US004

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to assign skills to a collaborator
    activate System

        System --> HRM : shows the list of collaborators and requests to select one
    deactivate System

    HRM -> System : selects a collaborator
    activate System

        System --> HRM : shows the list of skills and requests to select one or more
    deactivate System

    HRM -> System : selects one or more skills
    activate System

        System --> HRM : shows all data and requests confirmation
    deactivate System

    HRM -> System : confirms data
    activate System

        System --> HRM : shows success message (skill(s) assigned successfully)
    deactivate System
@enduml