@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Global Use Case Diagram

left to right direction

rectangle "System User" as actors {
    actor HRM
    actor VFM
    actor GSM
    actor QAM
    actor GSU
    actor CLB
}

rectangle "Use Cases" as usecases{
    usecase "US001/UC001 - Register a Skill" as UC001
    HRM --> UC001
}

rectangle "Use Cases" as usecases{
    usecase "US002/UC002 - Register a Job" as UC002
    HRM --> UC002
}

rectangle "Use Cases" as usecases{
    usecase "US003/UC003 - Register a collaborator with a job\n and fundamental characteristics." as UC003
    HRM --> UC003
}

rectangle "Use Cases" as usecases{
    usecase "US004/UC004 - Assign skills to a collaborator" as UC004
    HRM --> UC004
}

rectangle "Use Cases" as usecases{
    usecase "US005/UC005 - Generate a team" as UC005
    HRM --> UC005
}

rectangle "Use Cases" as usecases{
    usecase "US006/UC006 - Register a vehicle" as UC006
    VFM --> UC006
}

rectangle "Use Cases" as usecases{
    usecase "US007/UC007 - Register a Vehicle checkup" as UC007
    VFM --> UC007
}

rectangle "Use Cases" as usecases{
    usecase "US008/UC008 - List Vehicles Needing Check-up" as UC008
    VFM --> UC008
}

rectangle "Use Cases" as usecases{
    usecase "US009/UC009 - See the exact costs referring to \nwater consumption of specific green spaces" as UC009
    GSM --> UC009
}

rectangle "Use Cases" as usecases{
    usecase "US010/UC010 - See in a pie chart which piece(s) \nof equipment is/are used in each day" as UC010
    GSM --> UC010
}
rectangle "Use Cases" as usecases{
    usecase "US011/UC011 - Collect data from the user portal" as UC011
    GSM --> UC011
}
rectangle "Use Cases" as usecases{
    usecase "US012/UC012 - I want to import a .csv file containing routes" as UC012
    GSM --> UC012
}
rectangle "Use Cases" as usecases{
    usecase "US013/UC013 - Apply an algorithm that returns the \nroutes to be opened, with minimum cost" as UC013
    GSM --> UC013
}
rectangle "Use Cases" as usecases{
    usecase "US014/UC014 - Run tests for inputs of variable size,\nto observe the asymptotic behavior of the execution\ntime of the US13" as UC014
    QAM --> UC014
}

rectangle "Use Cases" as usecases{
    usecase "US015/UC015 - Predict the average monthly cost that will \nbe paid for water consumption." as UC015
    GSM --> UC015
}
rectangle "Use Cases" as usecases{
    usecase "US016/UC016 - Determine the best line that fits the data in US14." as UC016
    GSM --> UC016
}
rectangle "Use Cases" as usecases{
    usecase "US017/UC017 - I want to place signs to evacuate to an Assembly Point." as UC017
    GSM --> UC017
}
rectangle "Use Cases" as usecases{
    usecase "US018/UC018 - I want to place signs to evacuate to an Meeting Point." as UC018
    GSM --> UC018
}
rectangle "Use Cases" as usecases{
    usecase "US019/UC019 - Conclude about the worst-case time complexity of the \nprocedures developed in US13, US17, and US18." as UC019
    QAM --> UC019
}
rectangle "Use Cases" as usecases{
    usecase "US020/UC020 - I want to register a green space and its respective area." as UC020
    GSM --> UC020
}
rectangle "Use Cases" as usecases{
    usecase "US021/UC021 - I want to add a new entry to the To-Do List." as UC021
    GSM --> UC021
}
rectangle "Use Cases" as usecases{
    usecase "US022/UC022 - I want to add a new entry in the Agenda." as UC022
    GSM --> UC022
}
rectangle "Use Cases" as usecases{
    usecase "US023/UC023 - I want to assign a Team to an entry in the Agenda." as UC023
    GSM --> UC023
}
rectangle "Use Cases" as usecases{
    usecase "US024/UC024 - I want to Postpone an entry in the Agenda to a future date." as UC024
    GSM --> UC024
}
rectangle "Use Cases" as usecases{
    usecase "US025/UC025 - I want to Cancel an entry in the Agenda." as UC025
    GSM --> UC025
}
rectangle "Use Cases" as usecases{
    usecase "US026/UC026 - I want to assign one or more vehicles to an entry in the Agenda." as UC026
    GSM --> UC026
}
rectangle "Use Cases" as usecases{
    usecase "US027/UC027 - I need to list all green spaces managed by me." as UC027
    GSM --> UC027
}
rectangle "Use Cases" as usecases{
    usecase "US028/UC028 - I wish to consult the tasks assigned to me." as UC028
    CLB --> UC028
}
rectangle "Use Cases" as usecases{
    usecase "US029/UC029 - I want to record the completion of a task." as UC029
    CLB --> UC029
}
@enduml
