@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "vehicleRepository:\nVehicleRepository" as VehicleRepository

autonumber 8
-> VehicleRepository  : registerVehicle(VIN, Brand, Model, Type, Vehicle Plate, Tare Weight, \nGross Weight, Current Km, Registration date, Acquisition Date, Maintenance Frequency)

activate VehicleRepository
    group Verify Existing Vehicle
    autonumber 8.1

        VehicleRepository -> VehicleRepository: verifyExistingVehicle(VIN, Vehicle Plate)
        activate VehicleRepository

        VehicleRepository --> VehicleRepository
        deactivate VehicleRepository

    end
deactivate VehicleRepository


@enduml