@startuml
skinparam shadowing false
skinparam line type polyline

'left to right direction
package UI {
    class RegisterGreenSpaceUI {
        - controller : RegisterGreenSpaceController
        + RegisterGreenSpaceUI()
        + createNewGS() : void
        '- parseAddress(street : String, zipcode : String, city : String) : Address
    }
}

package CONTROLLER {
    class RegisterGreenSpaceController {
        - repositories: Repositories
        - greenSpaceRepository : GreenSpaceRepository
        + createNewGS(greenSpaceDto : GreenSpaceDto) : void
        + RegisterGreenSpaceController()
    }
}

package DOMAIN {
package REPOSITORY {
    class Repositories {
        - instance : Repositories
        - greenSpaceRepository : GreenSpaceRepository
        - Repositories()
        + getInstance() : Repositories
        + getGreenSpaceRepository() : GreenSpaceRepository
    }

    class GreenSpaceRepository {
        - greenSpaceList : List<GreenSpace>
        + GreenSpaceRepository()
        + create(greenSpaceDto : GreenSpaceDto) : void
        - addGreenSpace(greenSpace : GreenSpace) : void
        - verifyDuplicates(greenSpace : GreenSpace) : Boolean
    }
    }
package MODEL{
    class GreenSpace {
        - name : String
        - type : GreenSpaceType
        - area : Double
        - manager : UserSession
        - address : Address
        + GreenSpace(name : String, type : String, area : Double, address : Address, manager : UserSession)
        + verifyFilled(greenSpace: GreenSpace) : Boolean
    }
}
}
package DTO{
    class GreenSpaceDto{
        - name : String
        - type : GreenSpaceType
        - area : Double
        - manager : UserSession
        - address : String
        - city : String
        - zipCode : String
        + getName() : String
        + getType() : GreenSpaceType
        + getArea() : Double
        + getManager() : UserSession
        + getAddress() : String
        + getCity() : String
        + getZipCode() : String
    }

    class GreenSpaceMapper{
        +toDto(greenSpace : GreenSpace) : GreenSpaceDto
        +toDomain(greenSpaceDto : GreenSpaceDto) : GreenSpace
    }
    }

RegisterGreenSpaceUI ..> RegisterGreenSpaceController
RegisterGreenSpaceController ..> Repositories: repositories
Repositories --> Repositories: instance
RegisterGreenSpaceController ..> GreenSpaceRepository: greenSpaceRepository
Repositories --> "1"GreenSpaceRepository: greenSpaceRepository
GreenSpaceRepository -->"*" GreenSpace: greenSpaceRepository
RegisterGreenSpaceUI ..> GreenSpaceDto
GreenSpaceRepository ..> GreenSpaceMapper
GreenSpaceMapper ..> GreenSpace
GreenSpaceMapper ..> GreenSpaceDto

@enduml
