@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle\n:Vehicle" as VEI

activate VFM

    VFM -> UI : asks to register a new vehicle
    activate UI

        UI -> CTRL** : create

        UI --> VFM : requests vehicle data (VIN, Brand, Model, Type, Vehicle Plate, Tare Weight, \nGross Weight, Current Km, Registration date, Acquisition Date, Maintenance Frequency)
        deactivate UI

    VFM -> UI : types requested vehicle
    activate UI

    UI --> VFM : shows all data and requests confirmation
    deactivate UI

    VFM -> UI: confirms Data
    activate UI

        UI -> CTRL : submit vehicle data
        deactivate UI
        activate CTRL

            ref over CTRL
                                            Get Vehicle Repository

                                        end ref

        CTRL -> VehicleRepository : registerVehicle(VIN, Brand, Model, Type, Vehicle Plate, Tare Weight, \nGross Weight, Current Km, Registration date, Acquisition Date, Maintenance Frequency)
        deactivate CTRL

            activate VehicleRepository

        ref over VehicleRepository
                                                                            Verify Existing Vehicle

                                                                        end ref


            VehicleRepository -> VEI **: registerVehicle(VIN, Brand, Model, Type, Vehicle Plate, Tare Weight, \nGross Weight, Current Km, Registration date, Acquisition Date, Maintenance Frequency)
        deactivate VehicleRepository
            activate VEI


            ref over VEI
                                            Register Vehicle

                                        end ref

            VEI --> VehicleRepository: vehicle
            deactivate VEI
            activate VehicleRepository




            VehicleRepository -> VehicleRepository: addVehicle(vehicle)
            VehicleRepository --> CTRL: success
                        deactivate VehicleRepository

            activate CTRL


            CTRL --> UI : success
            deactivate CTRL
            activate UI

    UI --> VFM : displays success message (Vehicle registered successfully)
    deactivate UI

deactivate VFM

@enduml
