@startuml
skinparam shadowing false
skinparam line type polyline

'left to right direction
package UI {
    class RegisterGreenSpaceUI {
        - controller : RegisterGreenSpaceController
    }
}

package CONTROLLER {
    class RegisterGreenSpaceController {
        - repositories: Repositories
        - greenSpaceRepository : GreenSpaceRepository
        + createNewGS(name : String, street : String, zipCode : String, area : Double, city : String, type : GreenSpaceType ) : void
        + RegisterGreenSpaceController()
    }
}

package DOMAIN {
package REPOSITORY {
    class Repositories {
        - instance : Repositories
        - greenSpaceRepository : GreenSpaceRepository
        - Repositories()
        + getInstance() : Repositories
        + getGreenSpaceRepository() : GreenSpaceRepository
    }

    class GreenSpaceRepository {
        - greenSpaceList : List<GreenSpace>
        + GreenSpaceRepository()
        + create(greenSpaceDto : GreenSpaceDto) : void
        - addGreenSpace(greenSpace : GreenSpace) : void
        - verifyDuplicates(greenSpace : GreenSpace) : Boolean
    }
    }
package MODEL{
    class GreenSpace {
        - name : String
        - type : GreenSpaceType
        - area : Double
        - manager : String
        - address : Address
        + GreenSpace(name : String, type : String, area : Double, address : Address, manager : String)
        + setName(name : String) : Boolean
        + setType(type : GreenSpaceType) : Boolean
        + setArea(area : Double) : Boolean
    }
       enum GreenSpaceType{
       +GARDEN
       +MEDIUM-SIZED-PARK
       +LARGE-SIZED-PARK
       }
}
}
package DTO{
    class GreenSpaceDto{
        - name : String
        - type : GreenSpaceType
        - area : Double
        - manager : String
        - address : String
        - city : String
        - zipCode : String
        + getName() : String
        + getType() : GreenSpaceType
        + getArea() : Double
        + getManager() : String
        + getAddress() : String
        + getCity() : String
        + getZipCode() : String
    }

    class GreenSpaceMapper{
        +toDto(greenSpace : GreenSpace) : GreenSpaceDto
        +toDomain(greenSpaceDto : GreenSpaceDto) : GreenSpace
    }
    }
    package EXTERNAL{
    class ApplicationSession{
            +getInstance : ApplicationSession
            +getSortAlgorithmClassName : String
            +getCurrentSession : UserSession
    }
    }

RegisterGreenSpaceUI ..> RegisterGreenSpaceController
RegisterGreenSpaceController ..> Repositories: repositories
Repositories --> Repositories: instance
RegisterGreenSpaceController ..> GreenSpaceRepository: greenSpaceRepository
Repositories --> "1"GreenSpaceRepository: greenSpaceRepository
GreenSpaceRepository -->"*" GreenSpace: greenSpaceRepository
RegisterGreenSpaceUI ..> GreenSpaceDto
GreenSpaceRepository ..> GreenSpaceMapper
GreenSpaceMapper ..> GreenSpace
GreenSpaceMapper ..> GreenSpaceDto
GreenSpace ..> GreenSpaceType
ApplicationSession --> ApplicationSession: instance

RegisterGreenSpaceController ..> ApplicationSession  : getCurrentSession

@enduml
