
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'title System Sequence Diagram (SSD) - US020

autonumber

actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as gsrepo
participant ":GreenSpace" as GS

activate GSM

    GSM -> UI : wants to register a new green space
    activate UI

        UI -> CTRL** : create

        UI --> GSM : requests data (name, type, area)
        deactivate UI
GSM -> UI : the user enters and selects the data
activate UI
UI-> GSM : shows data and requests confirmation
deactivate UI
GSM -> UI: user confirms
activate UI
UI -> CTRL : createNewGS(name, type, area)
deactivate UI
activate CTRL
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton
CTRL -> PLAT : getGreenSpaceRepository()
activate PLAT
PLAT -->  CTRL: greenSpaceRepository
deactivate PLAT
CTRL -> gsrepo : createNewGS(name, type, area)
deactivate CTRL
activate gsrepo
gsrepo -> GS** : create(name, type, area)
activate GS
GS -> GS : verifyFilled(greenSpace)
activate GS
GS--> GS
deactivate GS
GS --> gsrepo : greenSpace
deactivate GS
gsrepo -> gsrepo : verify duplicates by name
activate gsrepo
gsrepo -> gsrepo : addGreenSpace(greenSpace)
activate gsrepo
gsrepo-->gsrepo
deactivate gsrepo
gsrepo-->gsrepo
deactivate gsrepo
gsrepo --> CTRL : greenSpace
deactivate gsrepo
activate CTRL
CTRL --> UI : success
deactivate CTRL
activate UI
UI-->GSM:displays success message
deactivate UI
deactivate GSM

@enduml
