
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'title System Sequence Diagram (SSD) - US020

autonumber

actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as gsrepo
participant ":GreenSpaceMapper" as GSMP
participant "greenSpace\n:GreenSpace" as GS
participant "greenSpaceDto\n:GreenSpaceDto" as DTO

activate GSM

    GSM -> UI : wants to register a new green space
    activate UI

        UI -> CTRL** : create
activate CTRL
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton
CTRL -> PLAT : getGreenSpaceRepository()
activate PLAT
PLAT -->  CTRL: greenSpaceRepository
deactivate PLAT
deactivate CTRL
        UI --> GSM : requests data (name, type, area, manager, \naddress (street, zip-code, city))
        deactivate UI
GSM -> UI : the user enters and selects the data
activate UI
UI-> GSM : shows data and requests confirmation
deactivate UI
GSM -> UI: user confirms
activate UI

UI->DTO** : GreenSpaceDto(name, type, area, manager, street, zipCode, city)
activate DTO
DTO -> DTO : this.name = name
DTO -> DTO : this.type = type
DTO -> DTO : this.area = area
DTO -> DTO : this.manager = manager
DTO -> DTO : this.address = address
DTO -> DTO : this.city = city
DTO -> DTO : this.zipCode = zipCode
DTO --> UI : greenSpaceDto
deactivate DTO

UI -> CTRL : createNewGS(greenSpaceDto)
deactivate UI
activate CTRL
CTRL -> gsrepo : createNewGS(greenSpaceDto)
deactivate CTRL
activate gsrepo
gsrepo -> GSMP : toDomain(greenSpaceDto)
activate GSMP

GSMP -> GS** : create

activate GS
GS -> GS : setArea(greenSpaceDto.getArea)
activate GS
GS --> GS
deactivate GS

GS -> GS : setName(greenSpaceDto.getName)
activate GS
GS --> GS
deactivate GS

GS -> GS : this.type = greenSpaceDto.getType

GS -> GS : this.manager = greenSpaceDto.getManager
GS -> GS : this.address = greenSpaceDto.getAddress

GS --> GSMP : greenSpace
deactivate GS
GSMP --> gsrepo : greenSpace
deactivate GSMP
gsrepo -> gsrepo : checkForDuplicates(greenSpace)
activate gsrepo
gsrepo -> gsrepo : addGreenSpace(greenSpace)
activate gsrepo
gsrepo-->gsrepo
deactivate gsrepo
gsrepo-->gsrepo
deactivate gsrepo
gsrepo --> CTRL : success
deactivate gsrepo
activate CTRL
CTRL --> UI : success
deactivate CTRL
activate UI
UI-->GSM:displays success message
deactivate UI
deactivate GSM

@enduml
