@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

autonumber 7


activate CTRL

 -> CTRL: createNewGS(name, type, area, loggedUser)

    group Get Green Space Repository


CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton
CTRL -> PLAT : getGreenSpaceRepository()
activate PLAT
PLAT -->  CTRL: greenSpaceRepository
deactivate PLAT

    end
deactivate CTRL


@enduml