@startuml
skinparam shadowing false
skinparam line type polyline

'left to right direction

    class RegisterGreenSpaceUI {
        - controller : RegisterGreenSpaceController
        + RegisterGreenSpaceUI()
        + createNewGS(name : String, type : String, area : Double, street : String, zipcode : String, city : String, manager : UserSession) : void
    }

    class RegisterGreenSpaceController {
        - repositories: Repositories
        - greenSpaceRepository : GreenSpaceRepository
        + createNewGS(name : String, type : String, area : Double, street : String, zipcode : String, city : String, manager : UserSession) : void
        + RegisterGreenSpaceController()
        - parseAddress(street : String, zipcode : String, city : String) : Address
    }

    class Repositories {
        - instance : Repositories
        - greenSpaceRepository : GreenSpaceRepository
        - Repositories()
        + getInstance() : Repositories
        + getGreenSpaceRepository() : GreenSpaceRepository
    }

    class GreenSpaceRepository {
        - greenSpaceList : List<GreenSpace>

        + GreenSpaceRepository()
        + create(name : String, type : String, area : Double, address : Address, manager : UserSession) : void
        + addGreenSpace(greenSpace: GreenSpace) : void
        + verifyDuplicates(greenSpace: GreenSpace) : Boolean
    }

    class GreenSpace {
        - name : String
        - type : String
        - area : Double
        - manager : Collaborator
        - address : Address
        + GreenSpace(name : String, type : String, area : Double, address : Address, manager : UserSession)
        + verifyFilled(greenSpace: GreenSpace) : Boolean
    }

RegisterGreenSpaceUI ..> RegisterGreenSpaceController
RegisterGreenSpaceController ..> Repositories: repositories
Repositories --> Repositories: instance
RegisterGreenSpaceController ..> GreenSpaceRepository: greenSpaceRepository
Repositories --> "1"GreenSpaceRepository: greenSpaceRepository
GreenSpaceRepository -->"*" GreenSpace: greenSpaceRepository

@enduml
