
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'title System Sequence Diagram (SSD) - US020

autonumber

actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as gsrepo
participant ":GreenSpace" as GS

activate GSM

    GSM -> UI : wants to register a new green space
    activate UI

        UI -> CTRL** : create
activate CTRL
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton
CTRL -> PLAT : getGreenSpaceRepository()
activate PLAT
PLAT -->  CTRL: greenSpaceRepository
deactivate PLAT
deactivate CTRL
        UI --> GSM : requests data (name, type, area, manager, \naddress (street, zip-code, city))
        deactivate UI
GSM -> UI : the user enters and selects the data
activate UI
UI-> GSM : shows data and requests confirmation
deactivate UI
GSM -> UI: user confirms
activate UI
UI -> CTRL : createNewGS(name, type, area, manager, \naddress (street, zip-code, city))
deactivate UI
activate CTRL
CTRL -> gsrepo : createNewGS(name, type, area, manager, address)
deactivate CTRL
activate gsrepo
gsrepo -> GS** : create(name, type, area, manager, address)

activate GS
GS -> GS : setArea(area)
activate GS
GS --> GS
deactivate GS

GS -> GS : setName(area)
activate GS
GS --> GS
deactivate GS

GS -> GS : this.type = type

GS -> GS : this.manager = manager
GS -> GS : this.address = address

GS --> gsrepo : greenSpace
deactivate GS
gsrepo -> gsrepo : checkForDuplicates(greenSpace)
activate gsrepo
gsrepo -> gsrepo : addGreenSpace(greenSpace)
activate gsrepo
gsrepo-->gsrepo
deactivate gsrepo
gsrepo-->gsrepo
deactivate gsrepo
gsrepo --> CTRL : success
deactivate gsrepo
activate CTRL
CTRL --> UI : success
deactivate CTRL
activate UI
UI-->GSM:displays success message
deactivate UI
deactivate GSM

@enduml
