@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC3

left to right direction

rectangle "System User" as actors {
    actor HRM
}

note right of HRM
    I want to register a collaborator with a job and fundamental
    characteristics.
end note

rectangle "Use Cases" as usecases{
    usecase "US03 - Register a collaborator and his attributes" as US03
    HRM --> US03
}

@enduml
