@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC5

left to right direction

rectangle "System User" as actors {
    actor HRM
}

note right of HRM
     I want to generate a team proposal automatically.
end note

rectangle "Use Cases" as usecases{
    usecase "US05 - Generate a new team, based on the needs" as US05
    HRM --> US05
}

@enduml
