@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC6

left to right direction

rectangle "System User" as actors {
    actor FM
}

note right of FM
    I wish to register a vehicle including Brand, Model, Type, Tare,
    Gross Weight, Current Km, Register Date, Acquisition Date,
    Maintenance/Checkup Frequency (in Kms).
end note

rectangle "Use Cases" as usecases{
    usecase "US06 - Register a vehicle with his attributes" as US06
    FM --> US06
}

@enduml
