@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UC7

left to right direction

rectangle "System User" as actors {
    actor FM
}

note right of FM
     I wish to register a vehicle’s check-up.
end note

rectangle "Use Cases" as usecases{
    usecase "US07 - Schedule a vehicle check-up" as US07
    FM --> US07
}

@enduml
