@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US028

autonumber

actor "CLB" as CLB
participant ":System" as System

activate CLB

    CLB -> System : asks to consult the entry assigned to himself
    activate System

        System --> CLB : displays greens spaces sorted by date
    deactivate System
@enduml