@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class VehicleCheckup {
    date
    currentKm
    vehicleID
}

class Vehicle{
vin
vehiclePlate
tareWeight
grossWeight
currentKm
registrationDate
acquisitionDate
maintenanceFrequency
type

}

Vehicle "1" - "1..*" VehicleCheckup : needs >
@enduml