@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction

title Domain Model

class HRM {
}

class FM{
}

class Skill {
    designation
}

class Job {
    title
    description
}

class Collaborator {
    admissionDate
}

class DocumentType{
    identificationCode
}


class Team {
    name
}

class Vehicle {
    vin
    vehiclePlate
    tareWeight
    grossWeight
    currentKm
    acquisitionDate
    maintenanceFrequency
    type
}

class Brand{
    model
}

class VehicleCheckup{
    date
    currentKm
}

class Person {
    name
    birthdate
    contact
}

class Address{
    zipCode
    city
}

Vehicle "1" -- "1..*" Brand : has >

HRM "*" -- "1..*" Skill : creates >

HRM "*" -- "1..*" Job : creates >

Collaborator  "1" -- "1"  Person : is >
Person "1" -- "1" DocumentType : has an >
HRM "*" -- "1" Collaborator : registers >
'HRM -- "1" Job : assigns >
Job "1" -- "1..*" Collaborator : to >

'HRM "1" -- "1..*" Skill : assigns >
Skill "*" -- "1..*" Collaborator : to >

HRM "*" -- "1" Team: generate   >
Team "*" -- "1..*" Collaborator : has >

FM "1" - "*" Vehicle : creates  >

FM "1" - "*" VehicleCheckup : registers >

Vehicle "1" -- "*" VehicleCheckup : has >


Person "1" -- "1" Address : has a >

@enduml