@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class Vehicle {
vin
vehiclePlate
tareWeight
grossWeight
currentKm
acquisitionDate
maintenanceFrequency
type
}

class Brand {
    designation
}

class Model {
    designation
}

Vehicle "1..*" - "1" Brand : has >
Model "1..*" -"1" Brand: has <
@enduml