@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class Team {
    teamId
    maxNumberElements
    minNumberElements
}

class Collaborator {
    admissionDate
}

class Skill{
    designation
}


class Person {
    name
    birthdate
    contactMobile
    email
    taxpayerNumber
}

class Address{
    street
    zipCode
    city
}

class Document{
    documentType
    identificationCode
}

Person "1" -- "1" Address: has an >
Collaborator "1" -- "1"  Person: is a >
Person "1" -- "1..*"  Document: has >
Team "1" -- "1..*" Collaborator : has >
Skill "1..*" -- "1..*" Team: needs <


@enduml
