@startuml
skinparam shadowing false
skinparam linetype polyline


skinparam classAttributeIconSize 0



class FleetManager {
}

class VehicleCheckup {
    - String plateNumber
    - String date
    - String kmAtCheckup
}


class MaintenanceRepository {
    + registerVehicleCheckup(plateNumber, date, kmAtCheckup)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getMaintenanceRepository()
}

class RegisterMaintenanceController {
    + RegisterMaintenanceController()
    + getMaintenanceRepository()
}

class RegisterMaintenanceUI {
}

Repositories -> Repositories : instance

RegisterMaintenanceUI .> RegisterMaintenanceController

RegisterMaintenanceController .> Repositories

RegisterMaintenanceController ..> MaintenanceRepository

Repositories -> "1" MaintenanceRepository

MaintenanceRepository "1" -> "*" VehicleCheckup


RegisterMaintenanceController ..> VehicleCheckup

VehicleCheckup "*" --> "*" FleetManager : registered by

@enduml
