@startuml
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterMaintenanceUI" as UI
participant ":RegisterMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "maintenanceRepository:\nMaintenanceRepository" as MaintenanceRepository
participant ":Maintenance" as Maintenance

activate VFM

    VFM -> UI : requests to list vehicles needing maintenance
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getVehiclesList()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getVehicleRepository()
            activate PLAT

                PLAT --> CTRL: VehicleRepository
            deactivate PLAT

            CTRL -> VehicleRepository : getVehiclesList()
            activate VehicleRepository

                VehicleRepository --> CTRL : vehicleList
            deactivate VehicleRepository

            CTRL --> UI : vehicleList
            deactivate CTRL

            UI --> VFM : displays vehicle List
            deactivate UI

            VFM -> UI : chooses vehicle
            activate UI

            UI -> CTRL : vehicle
            activate CTRL

            CTRL --> UI : requests data(date, current Km)
            deactivate CTRL

            UI --> VFM : requests data (date, current Km)
            deactivate

            VFM -> UI : types data (date, current Km)
            activate UI

            UI -> CTRL : data (date, current Km)
            activate CTRL

            CTRL -> PLAT : getMaintenanceRepository()
            activate PLAT

            PLAT --> CTRL : MaintenanceRepository
            deactivate

            CTRL -> MaintenanceRepository : register maintenance
            activate MaintenanceRepository

            MaintenanceRepository -> Maintenance** : create(date, current Km)
            activate Maintenance

                Maintenance -> Maintenance : verifyFilled(maintenance)
                Maintenance -> Maintenance : verifySpecialCharacters(maintenance)
                Maintenance --> MaintenanceRepository : maintenance
               deactivate
               MaintenanceRepository --> CTRL : maintenance
               deactivate
               CTRL --> UI : maintenance
               deactivate
               UI --> VFM : displays maintenance data
               UI --> VFM : requests confirmation
               deactivate
               VFM -> UI : confirms data
               activate UI

               UI -> CTRL : confirmation
               activate CTRL

               CTRL --> UI : operation success
               deactivate
               UI -> VFM : displays operation success
               deactivate

               deactivate VFM


@enduml