@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterMaintenanceUI" as UI
participant ":RegisterMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "maintenanceRepository:\nMaintenanceRepository" as MaintenanceRepository
participant ":Maintenance" as Maintenance

activate VFM

    VFM -> UI : requests to list vehicles needing maintenance
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getVehiclesList()
        deactivate UI
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getVehicleRepository()
            activate PLAT

                PLAT --> CTRL: VehicleRepository
            deactivate PLAT

            CTRL -> VehicleRepository : getVehiclesList()
            activate VehicleRepository

                VehicleRepository --> CTRL : vehicleList
            deactivate VehicleRepository

            CTRL --> UI : vehicleList
            deactivate CTRL
            activate UI

            UI --> VFM : displays vehicle List

            VFM -> UI : chooses vehicle

            UI -> CTRL : vehicle
            activate CTRL

            CTRL --> UI : requests data(date, current Km)
            deactivate CTRL

            UI --> VFM : requests data (date, current Km)

            VFM -> UI : types data (date, current Km)


            UI -> CTRL : data (date, current Km)
            deactivate UI
            activate CTRL


            CTRL -> PLAT : getMaintenanceRepository()
            activate PLAT

            PLAT --> CTRL : MaintenanceRepository
            deactivate PLAT

            CTRL -> MaintenanceRepository : register maintenance
            activate MaintenanceRepository

            MaintenanceRepository -> Maintenance** : create(date, current Km)
            activate Maintenance

                Maintenance -> Maintenance : verifyFilled(maintenance)
                activate Maintenance
                Maintenance -> Maintenance : verifySpecialCharacters(maintenance)
                activate Maintenance
                Maintenance --> Maintenance
                deactivate Maintenance
                Maintenance --> Maintenance
                deactivate Maintenance

                Maintenance --> MaintenanceRepository : maintenance
               deactivate Maintenance
               MaintenanceRepository --> CTRL : maintenance
               deactivate MaintenanceRepository
               CTRL --> UI : maintenance
               deactivate CTRL
               activate UI

               UI --> VFM : displays maintenance data and requests confirmation
               VFM -> UI : confirms data

               UI -> CTRL : confirmation
               activate CTRL

               CTRL --> UI : operation success
               deactivate CTRL

               UI --> VFM : displays operation success
               deactivate UI

               deactivate VFM


@enduml