@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "GSM" as GSM
participant ":AddAgendaEntryUI" as UI
participant ":AddAgendaEntryController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "toDoRepository\n:ToDoRepository" as TODOREP
participant "agendaRepository\n:AgendaRepository" as AGENDREP

activate GSM
GSM -> UI : requests to add a new entry in the Agenda
activate UI


UI -> CTRL: get toDoList
activate CTRL

CTRL -> GlobRepo : getInstance()
activate GlobRepo
GlobRepo --> CTRL : repositories
deactivate GlobRepo
CTRL -> PLAT : getToDoRepository()
activate PLAT
PLAT -->  CTRL: toDoRepository
deactivate PLAT

CTRL -> TODOREP : getToDoList()
activate TODOREP
TODOREP --> CTRL : toDoList
deactivate TODOREP
CTRL --> UI : toDoList
deactivate CTRL
UI --> GSM : shows the list of To-Do entries and requests to select one
deactivate UI

GSM -> UI : selects a To-Do entry
activate UI

UI --> GSM: shows all data and requests confirmation
deactivate UI

GSM -> UI: confirms data
activate UI

UI -> CTRL : add agenda entry
deactivate UI
activate CTRL

CTRL -> AGENDREP : addAgendaEntry(toDoEntry)
deactivate CTRL

activate AGENDREP
AGENDREP --> CTRL : agendaEntry
deactivate AGENDREP
activate CTRL
CTRL --> UI : success
deactivate CTRL
activate UI
UI --> GSM : shows success message (entry added successfully)
deactivate UI
deactivate GSM
@enduml
