@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "VFM" as VFM
participant ":System" as System

activate VFM

    VFM -> System : asks to assign a Team to an entry in the Agenda.
    activate System

        System --> VFM : shows teams and asks to select one.
    deactivate System

    VFM -> System : selects team

    activate System

        System --> VFM : shows the entries in the agenda and asks to select one
    deactivate System

    VFM -> System : select the entry
    activate System

        System --> VFM : shows all data and requests confirmation
    deactivate System

    VFM -> System : confirms
    activate System

        System --> VFM :  displays success message (Team assigned successfully)
    deactivate System

@enduml