@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US023

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to assign a Team to an entry in the Agenda
    activate System

        System --> GSM : shows teams and asks to select one
    deactivate System

    GSM -> System : selects team

    activate System

        System --> GSM : shows the entries in the agenda and asks to select one
    deactivate System

    GSM -> System : select the entry
    activate System

        System --> GSM : shows all data and requests confirmation
    deactivate System

    GSM -> System : confirms
    activate System

        System --> GSM :  displays success message (Team assigned successfully)
    deactivate System

@enduml