@startuml
skinparam shadowing false
skinparam line type polyline

class AddNewEntryUI {
    - controller : RegisterToDoEntryController
}

class RegisterToDoEntryController {
    - greenSpaceRepository : GreenSpaceRepository
    - entryRepository : EntryRepository
    + RegisterToDoEntryController()
    + getGreenSpacesDto() : List<GreenSpaceDTO>
    + createNewToDoEntry(greenSpace: GreenSpaceDTO, description: String, urgency: UrgencyStatus, expectedDuration: int) : Entry
}

enum UrgencyStatus{
+HIGH
+MEDIUM
+LOW
}

class Repositories {
    - instance : Repositories
    - greenSpaceRepository : GreenSpaceRepository
    - entryRepository : EntryRepository
    + getInstance() : Repositories
    + getGreenSpaceRepository() : GreenSpaceRepository
    + getEntryRepository() : EntryRepository
}

class GreenSpaceRepository {
    + getGreenSpaceList() : List<GreenSpace>
}

class EntryRepository {
    + createEntry(greenSpace: GreenSpaceDTO, description: String, urgency: UrgencyStatus, expectedDuration: int) : Entry
}

class Entry {
    - greenSpace : GreenSpaceDTO
    - description : String
    - urgency : UrgencyStatus
    - expectedDuration : int
    + Entry(greenSpace: GreenSpaceDTO, description: String, urgency: int, expectedDuration: int)
    + verifyFilled(description: String) : Boolean
    + verifyDuration(expectedDuration: int) : Boolean
}

class GreenSpaceDTO {

}

class GreenSpaceMapper {
}

AddNewEntryUI ..> RegisterToDoEntryController
Entry ..> UrgencyStatus
RegisterToDoEntryController ..> Repositories: repositories
Repositories --> Repositories: instance
RegisterToDoEntryController ..> GreenSpaceRepository
RegisterToDoEntryController ..> EntryRepository
Repositories --> "1" GreenSpaceRepository
Repositories --> "1" EntryRepository
RegisterToDoEntryController ..> GreenSpaceMapper

GreenSpaceMapper ..> GreenSpaceDTO
EntryRepository --> Entry

@enduml
