@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

class AddNewEntryUI {
}

class AddNewEntryController {
    - greenSpaceRepository : GreenSpaceRepository
    - entryRepository : EntryRepository
    + AddNewEntryController()
    + getGreenSpaceList() : List<GreenSpaceDTO>
    + createEntry(greenSpace: GreenSpaceDTO, description: String, urgency: int, expectedDuration: int) : Entry
}

class Repositories {
    - instance : Repositories
    - greenSpaceRepository : GreenSpaceRepository
    - entryRepository : EntryRepository
    + getInstance() : Repositories
    + getGreenSpaceRepository() : GreenSpaceRepository
    + getEntryRepository() : EntryRepository
}

class GreenSpaceRepository {
    + getGreenSpaceList() : List<GreenSpaceDTO>
}

class EntryRepository {
    + createEntry(greenSpace: GreenSpaceDTO, description: String, urgency: int, expectedDuration: int) : Entry
}

class Entry {
    - greenSpace : GreenSpaceDTO
    - description : String
    - urgency : int
    - expectedDuration : int
    + Entry(greenSpace: GreenSpaceDTO, description: String, urgency: int, expectedDuration: int)
    + verifyFilled(description: String) : Boolean
    + verifyDuration(expectedDuration: int) : Boolean
}

class GreenSpaceDTO {

}

class GreenSpaceMapper {
}

AddNewEntryUI ..> AddNewEntryController

AddNewEntryController ..> Repositories: repositories
Repositories --> Repositories: instance
AddNewEntryController ..> GreenSpaceRepository
AddNewEntryController ..> EntryRepository
Repositories --> "1" GreenSpaceRepository
Repositories --> "1" EntryRepository
AddNewEntryController ..> GreenSpaceMapper

GreenSpaceMapper ..> GreenSpaceDTO
EntryRepository --> Entry

@enduml
