@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox


autonumber 7



 -> EntryRep : createEntry(greenSpace, description, degree of urgency, approximate expected duration)
         group Create Entry
         activate EntryRep


         EntryRep -> Entry : createEntry(greenSpace, description, degree of urgency, approximate expected duration)
         deactivate EntryRep
         activate Entry

         Entry -> Entry : verifyFilled(description)
         activate Entry

         Entry -> Entry : verifyDuration(aproxExpDuration)
         activate Entry

         Entry --> Entry
         deactivate Entry

         Entry --> Entry
         deactivate Entry

         Entry -> EntryRep : Entry
         deactivate Entry
         activate EntryRep
         end
          <-- EntryRep : Entry


@enduml