
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

''title System Sequence Diagram (SSD) - US006

autonumber

actor "GSM" as GSM
participant ":AddNewEntryUI" as UI
participant ":AddNewEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nVehicleRepository" as GreenSpaceRepository
participant "entryRepository" as EntryRep
participant "entry" as Entry

activate GSM

    GSM -> UI : asks to add a new entry
    activate UI


        UI -> CTRL** : create

        UI -> CTRL : get list of green spaces
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        deactivate CTRL
        activate RepositorySingleton


        RepositorySingleton --> CTRL : repositories
        deactivate RepositorySingleton
        activate CTRL

        CTRL -> PLAT :getGreenSpaceRepository
        deactivate CTRL
        activate PLAT


        PLAT --> CTRL : GreenSpaceRepository
        deactivate PLAT
        activate CTRL


        CTRL -> GreenSpaceRepository : getGreenSpaceList()
        deactivate CTRL
        activate GreenSpaceRepository

        GreenSpaceRepository --> CTRL : greenSpaceList
        deactivate GreenSpaceRepository
        activate CTRL

        CTRL --> UI : greenSpaceList : List<GreenSpaceDTO>
        deactivate CTRL


        UI --> GSM : displays list of green spaces
        deactivate UI

        GSM -> UI : Selects the green space
        activate UI

        UI --> GSM : requests entry data (description, degree of urgency, and approximate expected duration)
        deactivate UI

        GSM -> UI : types requested data
        activate UI

        UI -> CTRL : createEntry(greenSpace, description, degree of urgency, approximate expected duration)
        deactivate UI
        activate CTRL


        CTRL -> PLAT : getEntryRepository()
        deactivate CTRL
        activate PLAT

        PLAT --> CTRL : entryRepository
        deactivate PLAT
        activate CTRL

        CTRL -> EntryRep : createEntry(greenSpace, description, degree of urgency, approximate expected duration)
        deactivate CTRL
        activate EntryRep

        EntryRep -> Entry** : createEntry(greenSpace, description, degree of urgency, approximate expected duration)
        deactivate EntryRep
        activate Entry

        Entry -> Entry : verifyFilled(description)
        activate Entry

        Entry -> Entry : verifyDuration(aproxExpDuration)
        activate Entry

        Entry --> Entry
        deactivate Entry

        Entry --> Entry
        deactivate Entry

        Entry -> EntryRep : Entry
        deactivate Entry
        activate EntryRep

        EntryRep --> CTRL : Entry
        deactivate EntryRep
        activate CTRL

        CTRL --> UI : Entry
        deactivate CTRL
        activate UI

    UI --> GSM : displays success message (Entry registered successfully)
    deactivate UI

deactivate GSM

@enduml
