@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
left to right direction

hide circle
hide methods


class VehicleCheckup {
    vehicleId
    date
    currentKm
}

class Vehicle {
vin
vehiclePlate
tareWeight
grossWeight
currentKm
acquisitionDate
maintenanceFrequency
type
}

class Brand {
    designation
}

class Model{
    designation
}


Vehicle "1"-- "1" Brand: has an >
Brand "1" -- "1..*" Model: has >
Vehicle "1" -- "*" VehicleCheckup : has >
@enduml
