@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant "jobRepository:\nJobRepository" as jobRepository
participant "collaborator\n:Collaborator" as CLB
participant "address\n:Address" as Address



activate HRM

HRM -> UI : asks to create a new collaborator
activate UI

UI -> CTRL** : create
activate CTRL
CTRL -> GlobRepo : getInstance()
activate GlobRepo
GlobRepo --> CTRL : repositories
deactivate GlobRepo
CTRL -> PLAT : getJobRepository()
activate PLAT
PLAT -->  CTRL: jobRepository
deactivate PLAT
CTRL -> PLAT : getCollaboratorRepository()
activate PLAT
PLAT -->  CTRL: collaboratorRepository
deactivate PLAT
deactivate CTRL

UI --> HRM : requests data (collaborator personal information)
deactivate UI

HRM -> UI : types requested data
activate UI

UI -> CTRL: getJobs()
deactivate UI

activate CTRL
CTRL -> jobRepository : getJobList()
activate jobRepository
jobRepository --> CTRL : jobsList
deactivate jobRepository
CTRL -->UI : jobsList
deactivate CTRL
activate UI

UI --> HRM : shows the list of jobs and requests to select one
deactivate UI


HRM -> UI : select the job
activate UI

UI --> HRM: shows all data and requests for confirmation
deactivate UI

HRM -> UI: confirms the data
activate UI

UI -> CTRL : createCLB(collDto : CollaboratorDto)

deactivate UI
activate CTRL



CTRL -> CLBREP : createCLB(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType, identificationNumber, admissionDate, job, taxpayerNumber)
deactivate CTRL

activate CLBREP
CLBREP->CLB** : create(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType, identificationNumber, admissionDate, job, taxpayerNumber)
activate CLB
CLB -> CLB : setName(name)
activate CLB
CLB -> CLB : verifyFilled(collaborator)
activate CLB
CLB -> CLB : containsSpecialCharacters(name)
activate CLB
CLB --> CLB
deactivate CLB
CLB --> CLB
deactivate CLB
CLB --> CLB
deactivate CLB


CLB -> CLB : setBirthdate(birthdate)
activate CLB
CLB -> CLB : verifyBirth(birthdate)
activate CLB
CLB --> CLB
deactivate CLB
CLB --> CLB
deactivate CLB


CLB -> CLB : setContactMobile(contactMobile)
activate CLB
CLB -> CLB : verifyNineDigits(contactMobile)
activate CLB
CLB --> CLB
deactivate CLB
CLB --> CLB
deactivate CLB


CLB -> CLB : setEmail(email)
activate CLB
CLB -> CLB : verifyEmail(email)
activate CLB
CLB --> CLB
deactivate CLB
CLB --> CLB
deactivate CLB

CLB -> Address** : setAddress(address, city, zipCode)
activate Address
Address -> Address : setZipcode(zipCode)
activate Address
Address -> Address : verifyZipCode(zipCode)
activate Address
Address --> Address
deactivate Address
Address --> Address
deactivate Address

Address -> Address : setCity(city)
activate Address
Address --> Address
deactivate Address

Address -> Address : setAddress(address)
activate Address
Address --> Address
deactivate Address

Address --> CLB : address

deactivate Address

CLB -> CLB : this.documentType = documentType

CLB -> CLB : setIdentificationNumber(identificationNumber)
activate CLB
CLB -> CLB : verifyIdentificationNumber(identificationNumber)
activate CLB
CLB --> CLB
deactivate CLB
CLB-->CLB
deactivate CLB


CLB -> CLB : setAdmissionDate(admissionDate)
activate CLB
CLB -> CLB : verifyAdmissionDate(admissionDate)
activate CLB
CLB --> CLB
deactivate CLB
CLB-->CLB
deactivate CLB


CLB -> CLB : setTaxPayerNumber(taxpayerNumber)
activate CLB
CLB -> CLB : verifyNineDigits(taxpayerNumber)
activate CLB
CLB --> CLB
deactivate CLB
CLB-->CLB
deactivate CLB

CLB -> CLB : setJob(job)
activate CLB
CLB --> CLB
deactivate CLB


CLB -->CLBREP : collaborator
deactivate CLB

CLBREP -> CLBREP : checkForDuplicates(collaborator : Collaborator)
activate CLBREP
CLBREP -> CLBREP: addCollaborator(collaborator)
activate CLBREP
CLBREP --> CLBREP
deactivate CLBREP
CLBREP --> CLBREP
deactivate CLBREP


CLBREP --> CTRL : success
deactivate CLBREP
activate CTRL



CTRL --> UI : success
deactivate CTRL
activate UI
UI --> HRM : shows success message (collaborator created successfully)
deactivate UI
deactivate HRM
@enduml
