@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":Agenda" as Agenda

autonumber 8
-> Agenda : postponeEntry(entry, newDate)

activate Agenda
    group Postpone a Entry in Agenda

    Agenda -> Agenda : validateNewDate(newDate)
    Agenda -> Agenda : updateENtryStatus(entry, POSTPONED)
    Agenda -> Agenda : setNewDate(entry, newDate)

    end

<-- Agenda: success
deactivate Agenda


@enduml