@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":PostponeAgendaEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:EntryRepository" as EntryRepo

autonumber 2

activate CTRL


    group Get Entry List

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> EntryRepo : getEntryRepository()
            activate EntryRepo

                EntryRepo --> CTRL : entryRepository
            deactivate EntryRepo

            CTRL -> EntryRepo :getEntryList()
            activate EntryRepo

            EntryRepo --> CTRL : entryList
            deactivate EntryRepo
    end
deactivate CTRL


@enduml