@startuml
skinparam shadowing false
skinparam line type polyline

package UI {
    class PostponeAgendaEntryUI {
    }
}

package CONTROLLER {
    class PostponeAgendaEntryController {
        - repositories: Repositories
        - entryRepository: EntryRepository
        + PostponeAgendaEntryController()
        + getAgendaEntryList(gsm: UserSession): List<AgendaEntryDto>
        + postponeEntry(agendaEntryDto: AgendaEntryDto, newDate: LocalDate): boolean
        - convertToAgendaEntry(agendaEntryDto: AgendaEntryDto): AgendaEntry
        - notifyTeam(agendaEntryDto: AgendaEntryDto, newDate: LocalDate): boolean
    }
}

package DOMAIN {
    package REPOSITORY {
        class Repositories {
            - instance: Repositories
            - entryRepository: EntryRepository
            - Repositories()
            + getInstance(): Repositories
            + getEntryRepository(): EntryRepository
        }

        class EntryRepository {
            - agendaEntryList: List<AgendaEntry>
            + EntryRepository()
            + getAgendaEntryListByGSM(gsm: UserSession): List<AgendaEntryDto>
            + updateAgendaEntry(agendaEntry: AgendaEntry, POSTPONED: ProgressStatus): boolean
            + setProgressStatus(status: ProgressStatus): void
            + addAgendaEntry(agendaEntry: AgendaEntry): void
        }
    }

    package DTO {
        class AgendaEntryMapper {
            + toDto(agendaEntry: AgendaEntry): AgendaEntryDto
            + toDomain(agendaEntryDto: AgendaEntryDto): AgendaEntry
            + toDtoList(agendaEntries: List<AgendaEntry>): List<AgendaEntryDto>
        }

        class AgendaEntryDto {
            - title: String
            - description: String
            - duration: int
            - urgencyStatus: UrgencyStatus
            - greenSpace: GreenSpaceDto
            - startingDate: LocalDate
            - progressStatus: ProgressStatus
            + AgendaEntryDto(title: String, description: String, duration: int, urgencyStatus: UrgencyStatus, greenSpace: GreenSpaceDto, startingDate: LocalDate, progressStatus: ProgressStatus)
            + getTitle(): String
            + getDescription(): String
            + getDuration(): int
            + getUrgencyStatus(): UrgencyStatus
            + getGreenSpace(): GreenSpaceDto
            + getStartingDate(): LocalDate
            + getProgressStatus(): ProgressStatus
        }
    }

    package MODEL {
        class AgendaEntry {
            - title: String
            - description: String
            - duration: int
            - urgencyStatus: UrgencyStatus
            - greenSpace: GreenSpace
            - startingDate: LocalDate
            - progressStatus: ProgressStatus
            + AgendaEntry(agendaEntry: AgendaEntry, newDate: LocalDate, progressStatus: PLANNED)
            + AgendaEntry(title: String, description: String, duration: int, urgencyStatus: UrgencyStatus, greenSpace: GreenSpace, startingDate: LocalDate, progressStatus: ProgressStatus)

        }

        class NotificationService {
            + getTeamByEntry(agendaEntry: AgendaEntry): Team
            + getCollaboratorsList(team: Team): List<Collaborator>
            + notifyTeam(collaboratorsList: List<Collaborator>, agendaEntry: AgendaEntry, newDate: LocalDate): boolean
        }
    }
}

PostponeAgendaEntryUI ..> PostponeAgendaEntryController
PostponeAgendaEntryController ..> Repositories
Repositories --> Repositories: instance
PostponeAgendaEntryController ..> EntryRepository
Repositories --> EntryRepository
EntryRepository --> "*" AgendaEntry
AgendaEntryMapper ..> AgendaEntryDto
AgendaEntryMapper ..> AgendaEntry
PostponeAgendaEntryController ..> NotificationService

@enduml
