@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods



class Entry {
    urgencyStatus
    estimatedDate
    progressStatus

}


class Task {
    title
    description

}

class Agenda{
}





Agenda "1" -- "1..*" Entry: has >

Entry "1" -- "1" Task: is >

@enduml
