@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'hide footbox

participant ":RecordEntryController" as CTRL
participant "TeamRepository:\nTeamRepository" as TeamRepository

autonumber 6


activate CTRL


    group Get Entry List

    CTRL -> TeamRepository : getEntryOfCollaborator()
    activate TeamRepository

    TeamRepository --> CTRL : entryList
    deactivate TeamRepository


    end
deactivate CTRL


@enduml