@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'hide footbox

participant ":RecordEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
autonumber 3


activate CTRL

    group Get Team Repository

            CTRL -> RepositorySingleton: getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getTeamRepository()
            activate PLAT

                PLAT --> CTRL: TeamRepository
            deactivate PLAT

    end
deactivate CTRL


@enduml