@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "CLB" as CLB
participant ":RecordEntryUI" as UI
participant ":RecordEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository:\n:EntryRepository" as EntryRepo
participant "teamRepository:\n:TeamRepository" as TeamRepo
participant "AgendaEntryMapper" as EntryMapper
participant "agendaEntryDto\n:AgendaEntryDto" as EntryDto
participant "agendaEntry\n:AgendaEntry" as AgendaEntry


activate CLB

    CLB -> UI : asks to record a complete agendaEntry
    activate UI

        UI -> CTRL** : create
        deactivate UI
        activate CTRL

            CTRL -> RepositorySingleton: getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getTeamRepository()
            activate PLAT

                PLAT --> CTRL: teamRepository
            deactivate PLAT

            CTRL -> PLAT : getEntryRepository()
            activate PLAT

                PLAT --> CTRL: entryRepository
            deactivate PLAT


        deactivate CTRL

        UI -> CTRL: getAgendaEntryOfCollaboratorList()
        activate UI
        activate CTRL

            CTRL -> EntryRepo: getAgendaEntriesList()
            activate EntryRepo

            EntryRepo --> CTRL: agendaEntryList
            deactivate EntryRepo

            CTRL -> AgendaEntryMapper: toDtoList
            deactivate CTRL
            activate AgendaEntryMapper

            loop

                AgendaEntryMapper -> agendaEntryDto**: create
                activate agendaEntryDto

                agendaEntryDto --> AgendaEntryMapper: agendaEntryDto
                deactivate agendaEntryDto

            end loop

            AgendaEntryMapper --> CTRL: agendaEntryDtoList
            deactivate AgendaEntryMapper
            activate CTRL

            CTRL -> TeamRepo: getAgendaEntriesAssignedToCollaborator(CLB, agendaEntryDtoList)
            deactivate CTRL
            activate TeamRepo


                TeamRepo --> CTRL: agendaEntryDtoList
            deactivate TeamRepo
        activate CTRL

        CTRL --> UI : agendaEntryDtoList
        deactivate CTRL

        UI -> CLB : shows the list of the agendaEntry assign to the collaborator and requests to select the one to record
    deactivate UI

    CLB -> UI : select an assigned agendaEntry
    activate UI

        UI --> CLB : show agendaEntry and requests confirmation
    deactivate UI

    CLB -> UI : confirms data
    activate UI

        UI -> CTRL : recordEntryCompletion(selectedAgendaEntryDto)
        deactivate UI
        activate CTRL

            CTRL -> EntryMapper : toDomain(selectedAgendaEntryDto)
            activate EntryMapper

                EntryMapper -> AgendaEntry** : create
                activate AgendaEntry

                AgendaEntry --> EntryMapper : agendaEntry
                deactivate AgendaEntry

                EntryMapper --> CTRL : agendaEntry
            deactivate EntryMapper

            CTRL -> EntryRepo : recordAgendaEntryCompletion(agendaEntry, COMPLETED)
            deactivate CTRL
            activate EntryRepo

                EntryRepo -> AgendaEntry : setStatus(COMPLETED)
                deactivate EntryRepo
                activate AgendaEntry

                AgendaEntry -> EntryRepo : success
                deactivate AgendaEntry
                activate EntryRepo

                EntryRepo -> AgendaEntry : setAvailable(agendaEntry)
                deactivate EntryRepo
                activate AgendaEntry

                AgendaEntry -> AgendaEntry : setTeamAvailable

                AgendaEntry --> EntryRepo : success
                deactivate AgendaEntry

                activate EntryRepo

            EntryRepo --> CTRL : success
            deactivate EntryRepo
            activate CTRL

            CTRL --> UI : success
        deactivate CTRL
        activate UI

        UI --> CLB : displays a success message (agendaEntry recorded as completed)
    deactivate UI

@enduml
