@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "TeamRepository:\nTeamRepository" as TeamRepository
participant "entry\n:Entry" as Entry

autonumber 13
-> TeamRepository : recordEntryCompletion(selectedEntry)
activate TeamRepository

    group Record Entry Completion

    TeamRepository -> Entry : recordEntryCompletion(selectedEntry)
    deactivate TeamRepository
    activate Entry

        Entry -> Entry : setStatus(complete)

    Entry --> TeamRepository : success
    deactivate Entry
    activate TeamRepository




    end

     <-- TeamRepository: success
deactivate TeamRepository


@enduml