@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction

title Domain Model

class Skill {
    designation
}

class Job {
    title
    description
}

class Collaborator {
    admissionDate
    name
    birthdate
    contactMobile
    email
    taxpayerNumber
}

class Document{
    documentType
    identificationNumber
}


class Team {
    teamId
    maxNumberElements
    minNumberElements
}

class Vehicle {
    vin
    vehiclePlate
    tareWeight
    grossWeight
    currentKm
    acquisitionDate
    maintenanceFrequency
    type
}

class Brand{
    designation
}

class Model{
    designation
}

class VehicleCheckup{
    vehicleId
    date
    currentKm
}

'class Person {
 '   name
 '   birthdate
 '   contactMobile
 '   email
  '  taxpayerNumber
'}

class Address{
    street
    zipCode
    city
}

class StatisticalAnalysis{
}

class StatsUserPortal{
}


class GreenSpace{
    name
}

class Task{
    designation
    date
}

class Equipment{
    designation
}

class Agenda{
}

class Portal{
}

Vehicle "1..*" -- "1" Brand : has >

Model "1..*" -- "1" Brand : has <

Collaborator "1" -- "1..*" Document : has >

Job "1" -- "1..*" Collaborator : to >


Skill "*" -- "1..*" Collaborator : to >
Team "1..**" -- "1..*" Skill : needs >


Team "1..*" -- "1..*" Collaborator : has >


Vehicle "1" -- "*" VehicleCheckup : has >


Collaborator "1..*" -- "1" Address : has a >

GreenSpace "1" -- "1" StatisticalAnalysis : is analysed >

GreenSpace "1" -- "1" Address : has an >

Task "1" -- "1..*" Vehicle : needs >

Task "1" -- "1" Team : is assigned >

Task "1" -- "1..*" Equipment : has >

GreenSpace "1" -- "1" Portal : is connected >

Portal "1" -- "1" StatsUserPortal : is analysed >

Agenda "1" -- "1..*" Task : has >
@enduml