@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 23

participant ":AssignSkillsController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "skillsRepository:\nSkillsRepository" as skillsRepository


-> CTRL : get skillsList
activate CTRL
group Get Skill List
CTRL -> GlobRepo : getInstance()
activate GlobRepo

GlobRepo --> CTRL : repositories
deactivate GlobRepo

CTRL -> PLAT : getSkillsRepository()
activate PLAT

PLAT -->  CTRL: skillsRepository
deactivate PLAT

CTRL -> skillsRepository : getSkills()
activate skillsRepository

skillsRepository --> CTRL : skillsList
deactivate skillsRepository
end
<-- CTRL : skillsList
deactivate CTRL

@enduml