@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "HRM" as HRM
participant ":AssignSkillsUI" as UI
participant ":AssignSkillsController" as CTRL
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant "skillsRepository:\nSkillsRepository" as skillsRepository


activate HRM

HRM -> UI : wants to assign skills to a collaborator
activate UI

UI -> CTRL** : create


activate CTRL
ref over CTRL
Get Collaborator List
end ref


CTRL --> UI : collaboratorList
deactivate CTRL

UI --> HRM : asks to select a collaborator
deactivate UI


HRM -> UI : selects a collaborator
activate UI

UI -> CTRL : collaborator
deactivate UI
activate CTRL


ref over CTRL
Get Skills List
end ref

CTRL --> UI : skillsList
deactivate CTRL
activate UI

UI --> HRM : displays available skills and asks to select one or more
deactivate UI

HRM -> UI : select the desired skills
activate UI
UI -> CTRL : selectedSkillsList
deactivate UI
activate CTRL


CTRL -> CLBREP : assignSkills(collaborator, selectedSkills[])
deactivate CTRL
activate CLBREP
ref over CLBREP
Assign Skills
end ref
CLBREP --> CTRL : collaborator
deactivate CLBREP
activate CTRL
CTRL -> UI : success
deactivate CTRL
activate UI
UI --> HRM : displays operation success
deactivate UI
deactivate HRM
@enduml