@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 23

participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant ":Collaborator" as CLB

-> CLBREP : assignSkills(collaborator, selectedSkills[])
activate CLBREP
group Assign skills
CLBREP -> CLB : assignSkills(selectedSkills[])
activate CLB
CLB -> CLB : setSkills(selectedSkills[])
CLB --> CLBREP : collaborator
deactivate CLB
end
<-- CLBREP : collaborator
deactivate CLBREP

@enduml