@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 23

participant ":AssignSkillsController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP



activate CTRL
group Get Collaborator List
CTRL -> GlobRepo : getInstance()
activate GlobRepo

GlobRepo --> CTRL : repositories
deactivate GlobRepo

CTRL -> PLAT : getCollaboratorRepository()
activate PLAT

PLAT -->  CTRL: collaboratorRepository
deactivate PLAT

CTRL -> CLBREP : getCollaboratorList()
activate CLBREP

CLBREP --> CTRL : collaboratorList
deactivate CLBREP
end
<-- CTRL : collaboratorList
deactivate CTRL

@enduml