@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

class AssignSkillsUI {
}

class AssignSkillsController {
    + assignSkills(skill : Skill) : void
    + getInstance() : CollaboratorRepository
    + getInstance() : SkillsRepository
}

class Repositories {
    + getCollaboratorRepository() : CollaboratorRepository
    + getSkillsRepository() : SkillsRepository
}

class CollaboratorRepository {
        + create(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType : String, identificationNumber : String, \nadmissionDate : Date, taxpayerNumber : int, job : Job)
        + checkForDuplicates() : void
        + addCollaborator(collaborator) : void
}

class SkillsRepository {
    + createSkill(name : String) : Skill
    + checkForDuplicates() : void
}

class Collaborator {
    - name : String
    - birthdate : Date
    - contactMobile : String
    - email : String
    - address : String
    - zipCode : String
    - city : String
    - admissionDate : Date
    - job : Job
    - taxpayerNumber : int
    + setSkills(selectedSkills : Skill[]) : void
}

class Skill {
    - name : String
    + Skill(title : String)
    + verifyFilled(skill : Skill) : void
    + verifySpecialCharacters(skill : Skill) : void
}

AssignSkillsUI ..> AssignSkillsController
AssignSkillsController ..> Repositories : repositories
Repositories --> Repositories : instance
Repositories --> "1" CollaboratorRepository : collaboratorRepository
Repositories --> "1" SkillsRepository : skillsRepository
AssignSkillsController ..> CollaboratorRepository : collaboratorRepository
AssignSkillsController ..> SkillsRepository : skillsRepository
CollaboratorRepository --> "*" Collaborator : collaborators
SkillsRepository --> "*" Skill : skills

@enduml
