
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

''title System Sequence Diagram (SSD) - US006

autonumber

actor "GSM" as GSM
participant ":ListGreenSpacesUI" as UI
participant ":ListGreenSpacesController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepo
participant ":GreenSpaceMapper" as mapper
participant "greenSpaceDto\n:GreenSpaceDto" as dto
participant ":ApplicationSession" as ApplicationSession
participant "applicationSession\n:ApplicationSession" as applicationSession1
participant "applicationSession\n:ApplicationSession" as applicationSession
participant ":Class" as Class
participant "sortable\n:Sortable" as SortAlgorithms

activate GSM
GSM -> UI : asks to list all green spaces managed by him
activate UI
UI -> CTRL** : create
activate CTRL
CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton
RepositorySingleton --> CTRL : repositories
deactivate RepositorySingleton
CTRL -> PLAT : getGreenSpaceRepository()
activate PLAT
PLAT -->  CTRL: greenSpaceRepository
deactivate CTRL

deactivate PLAT
UI -> CTRL : getOrganizedList()
deactivate UI
activate CTRL
CTRL -> ApplicationSession : getInstance
activate ApplicationSession
ApplicationSession --> CTRL : applicationSession
deactivate ApplicationSession
CTRL -> applicationSession1 : getCurrentSession()
activate applicationSession1
applicationSession1 --> CTRL : loggedUser
deactivate applicationSession1


CTRL -> GreenSpaceRepo : getList(loggedUser)
deactivate CTRL

activate GreenSpaceRepo
GreenSpaceRepo -> GreenSpaceRepo : getOrganizedList(loggedUser)
activate GreenSpaceRepo
GreenSpaceRepo -> GreenSpaceRepo : matchWithLoggedUser(loggedUser)
activate GreenSpaceRepo
GreenSpaceRepo --> GreenSpaceRepo
deactivate GreenSpaceRepo

GreenSpaceRepo -> ApplicationSession : getInstance()
activate ApplicationSession
ApplicationSession --> GreenSpaceRepo : applicationSession
deactivate ApplicationSession
GreenSpaceRepo -> applicationSession : getSortAlgorithmClassName()
activate applicationSession
applicationSession --> GreenSpaceRepo : algorithmClassName
deactivate applicationSession

GreenSpaceRepo -> Class : forName(algorithmClassName)
activate Class
Class --> GreenSpaceRepo : Class<?>
deactivate Class

GreenSpaceRepo -> SortAlgorithms** : newInstance()


GreenSpaceRepo -> GreenSpaceRepo : verifyEmptyList(listMatched)
activate GreenSpaceRepo

GreenSpaceRepo -> GreenSpaceRepo : sortable.sort(listMatched)
activate GreenSpaceRepo
GreenSpaceRepo -> mapper : toDtoList(listOrganized)
activate mapper

loop
mapper -> dto** : create
activate dto
dto --> mapper : greenSpaceDto
deactivate dto
mapper -> mapper : list.add(greenSpaceDto)
end loop

mapper --> GreenSpaceRepo : list
deactivate mapper
GreenSpaceRepo --> GreenSpaceRepo
deactivate GreenSpaceRepo
GreenSpaceRepo --> GreenSpaceRepo
deactivate GreenSpaceRepo
GreenSpaceRepo --> GreenSpaceRepo
deactivate GreenSpaceRepo

GreenSpaceRepo --> CTRL:list
deactivate GreenSpaceRepo
activate CTRL
CTRL --> UI : list

deactivate CTRL
activate UI
UI --> GSM : displays operation success by showing the list
deactivate UI
deactivate GSM

@enduml
