@startuml
skinparam shadowing false
skinparam line type polyline

'left to right direction
package UI{
    class ListGreenSpacesUI {
        - controller : ListGreenSpacesController
            }
}
package CONTROLLER {
    class ListGreenSpacesController {
        - repositories: Repositories
        - greenSpaceRepository : GreenSpaceRepository

        + ListGreenSpacesController()
        +getList(loggedUser : UserSession) : List<GreenSpace>
    }
}
package DOMAIN{
package REPOSITORY{
    class Repositories {
        - instance : Repositories
        - greenSpaceRepository : GreenSpaceRepository
        - Repositories()
        + getInstance() : Repositories
        + getGreenSpaceRepository() : GreenSpaceRepository
    }

    class GreenSpaceRepository {
        - greenSpaceList : List<GreenSpace>
        + GreenSpaceRepository()
        + getOrganizedList(loggedUser : UserSession) : List<GreenSpaceDto>
        - verifyEmptyList(listMatched : List<GreenSpace>) : Boolean
        - matchWithLoggedUser(loggedUser : UserSession) : List<GreenSpace>
    }
    }
package MODEL{
    class GreenSpace {
        - name : String
        - size : Double
        - manager : String
        + getManager() : String
        + getSize() : Double
    }
    }
    }
    package EXTERNAL{
    interface Sortable{
    +sort(g : List<GreenSpace>) : List<GreenSpace>
    }
    class SortByAscending{
    +sort(g : List<GreenSpace>) : List<GreenSpace>
    }
    class SortByDescending{
        +sort(g : List<GreenSpace>) : List<GreenSpace>
    }
    class SortByType{
        +sort(g : List<GreenSpace>) : List<GreenSpace>
    }
}
package DTO{
           class GreenSpaceDto{
                - name : String
                - type : GreenSpaceType
                - area : Double
                - manager : String
                - address : String
                - city : String
                - zipCode : String
                + getName() : String
                + getType() : GreenSpaceType
                + getArea() : Double
                + getManager() : String
                + getAddress() : String
                + getCity() : String
                + getZipCode() : String
            }

            class GreenSpaceMapper{
                +toDto(greenSpace : GreenSpace) : GreenSpaceDto
                +toDomain(greenSpaceDto : GreenSpaceDto) : GreenSpace
            }
        }


ListGreenSpacesUI ..> ListGreenSpacesController
ListGreenSpacesController ..> Repositories: repositories
Repositories --> Repositories: instance
ListGreenSpacesController ..> GreenSpaceRepository: greenSpaceRepository
Repositories --> "1"GreenSpaceRepository: greenSpaceRepository
GreenSpaceRepository -->"*" GreenSpace
GreenSpaceRepository ..> GreenSpaceMapper : toDto
GreenSpaceMapper ..> GreenSpaceDto
GreenSpaceRepository ..> Sortable : uses
Sortable --> SortByAscending : is implemented
Sortable --> SortByDescending : is implemented
Sortable --> SortByType : is implemented


@enduml
