@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

class HRM {
}

class RegisterCollaboratorUI {
}

class RegisterCollaboratorController {
    + createCollaborator()
    + assignJob()
    + assignSkills()
}

class Repositories {
    + getInstance()
}

class CollaboratorRepository {
    + createCollaborator()
    + checkForDuplicates()
}

class JobRepository {
    + getJobs()
}

class Collaborator {
    - name: String
    - birthdate: Date
    - contactMobile: String
    - email: String
    - address: String
    - zipCode: String
    - city: String
    - documentTypes: List<DocumentType>
    - admissionDate: Date
    - job: Job
    - skills: List<Skill>
}

class Job {
    - title: String
    - description: String
}

class DocumentType {
    - identificationCode: String
}

@enduml