@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

'left to right direction

class RegisterCollaboratorUI {
}

class RegisterCollaboratorController {
    + createCLB(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType, identificationNumber, admissionDate : Date, identificationNumber : String, job : Job)
    + getJobRepository() : JobRepository
    + getCollaboratorRepository() : CollaboratorRepository

}

class Repositories {
    -jobRepository: JobRepository
    -collaboratorRepository: CollaboratorRepository

    + getInstance(): Repositories
    +getJobRepository() : JobRepository
    +getCollaboratorRepository() : CollaboratorRepository
}

class CollaboratorRepository {
    + create(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType : String, identificationNumber : String, \nadmissionDate : Date, taxpayerNumber : int, job : Job)
    + checkForDuplicates() : void
    + addCollaborator(collaborator) : void

}

class JobRepository {
    +createJob(title : String) : Job
    +checkForDuplicates() : void
}

class Collaborator {
    - name : String
    - birthdate : Date
    - contactMobile : String
    - email : String
    - address : String
    - zipCode : String
    - city : String
    - admissionDate : Date
    - job : Job
    - taxpayerNumber : int
    + Collaborator(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType : String, identificationNumber : String, \nadmissionDate : Date, taxpayerNumber : int, job : Job)
    + verifyFilled(collaborator) : void
    + verifyMobile(collaborator) : void
    + verifyEmail(collaborator) : void
    + verifyZipCode(collaborator) : void
    + verifyBirth(collaborator) : void
    + verifyDocumentCode(collaborator) : void
    + verifyTaxpayerNumber(collaborator) : void
    - documentType : String
    - identificationNumber : String
}

class Job {
    - title : String
    + Job(title : String)
    +verifyFilled(job : Job) : void
    +verifySpecialCharacters(job : Job) : void
}



RegisterCollaboratorUI ..> RegisterCollaboratorController
RegisterCollaboratorController ..> Repositories : repositories
Repositories --> Repositories : instance
Repositories --> JobRepository : jobRepository
Repositories --> "1"CollaboratorRepository : collaboratorRepository
CollaboratorRepository --> "*" Collaborator : collaborators
RegisterCollaboratorController ..> CollaboratorRepository : collaboratorRepository
RegisterCollaboratorController ..> JobRepository : jobRepository
JobRepository --> "*" Job : jobs

@enduml