@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 28

participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT

-> CTRL: create collaborator
activate CTRL

group Get Collaborator Repository

CTRL -> GlobRepo : getInstance()
activate GlobRepo
GlobRepo --> CTRL : repositories
deactivate GlobRepo
CTRL -> PLAT : getCollaboratorRepository()
activate PLAT
PLAT -->  CTRL: collaboratorRepository
deactivate PLAT

end
@enduml
