@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

'left to right direction

class RegisterCollaboratorUI {
}

class RegisterCollaboratorController {
    + createCLB(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType, identificationNumber, admissionDate : Date, documentCode : String, job : Job)
    + assignJob(job : Job)
    + getInstance() : JobRepository
    + getInstance() : CollaboratorRepository

}

class Repositories {
    +getJobRepository() : JobRepository
    +getCollaboratorRepository() : CollaboratorRepository
}

class CollaboratorRepository {
    + create(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType, identificationNumber, admissionDate : Date, documentCode : String, job : Job)
    + checkForDuplicates()
}

class JobRepository {
    +createJob(title : String) : Job
    +checkForDuplicates() : void
}

class Collaborator {
    - name : String
    - birthdate : Date
    - contactMobile : String
    - email : String
    - address : String
    - zipCode : String
    - city : String
    - documentTypes : List<DocumentType>
    - admissionDate : Date
    - job : Job
    + Collaborator(name : String, birthdate : Date, contactMobile : String,\nemail : String, address : String, zipCode : String, city : String,\ndocumentType, identificationNumber, admissionDate : Date, documentCode : String, job : Job)
    + verifyFilled(collaborator)
    + verifyMobile(collaborator)
    + verifyEmail(collaborator)
    + verifyZipCode(collaborator)
    + verifyBirth(collaborator)
    + verifyDocumentCode(collaborator)
    - documentType : String
    - identificationNumber : String
}

class Job {
    - title : String
    + Job(title : String)
    +verifyFilled(job : Job) : void
    +verifySpecialCharacters(job : Job) : void
}



RegisterCollaboratorUI ..> RegisterCollaboratorController
RegisterCollaboratorController ..> Repositories : repositories
Repositories --> Repositories : instance
Repositories --> JobRepository : jobRepository
Repositories --> "1"CollaboratorRepository : collaboratorRepository
CollaboratorRepository --> "*" Collaborator : collaborators
RegisterCollaboratorController ..> CollaboratorRepository : collaboratorRepository
RegisterCollaboratorController ..> JobRepository : jobRepository
JobRepository --> "*" Job : jobs

@enduml