@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL

participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP


activate HRM
HRM -> UI : wants to register a new collaborator
activate UI
UI -> CTRL** : create
UI --> HRM : asks for the info needed (name, birthdate, contactMobile, email, address,\n zipCode, city, documentType[], documentCode, admissionDate)
HRM -> UI : provides the needed info
'UI --> HRM : shows a verification dialog
'HRM -> UI : confirms collaborator creation
UI -> CTRL : createCLB(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType[], documentCode, admissionDate)
deactivate UI
activate CTRL
        ref over CTRL
            Get Collaborator Repository
        end ref

CTRL -> CLBREP : createCLB(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType[], documentCode, admissionDate)
deactivate CTRL
activate CLBREP
        ref over CLBREP
            Create Collaborator
        end ref

activate CLBREP

CLBREP -> CLBREP : check for duplicates (documentCode[])
activate CLBREP
CLBREP --> CLBREP
deactivate CLBREP
CLBREP --> CTRL : collaborator
deactivate CLBREP
deactivate CLBREP

activate CTRL
ref over CTRL
                         Get Job List
                     end ref
CTRL -->UI : jobsList
deactivate CTRL
activate UI
UI --> HRM : shows the list of jobs and asks to select one
HRM -> UI : select the desired job
UI -> CTRL : job
deactivate UI
activate CTRL


CTRL ->CLBREP : assignJob(job)
deactivate CTRL
activate CLBREP

        ref over CLBREP
            Assign the chosen job
        end ref
CLBREP --> CTRL : collaborator
deactivate CLBREP
activate CTRL
CTRL -> UI : success
deactivate CTRL
activate UI
UI --> HRM : displays operation success
deactivate UI
deactivate HRM
@enduml
