@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant "jobRepository:\nJobRepository" as jobRepository
participant ":Collaborator" as CLB


activate HRM

HRM -> UI : asks to create a new collaborator
activate UI

UI -> CTRL** : create

UI --> HRM : requests data (collaborator personal information)
deactivate UI

HRM -> UI : types requested data
activate UI

UI -> CTRL: get job list
deactivate UI

activate CTRL

ref over CTRL
Get job List
end ref



deactivate jobRepository
CTRL -->UI : job list
deactivate CTRL
activate UI

UI --> HRM : shows the list of jobs and requests to select one
deactivate UI


HRM -> UI : select the job
activate UI

UI --> HRM: shows all data and requests for confirmation
deactivate UI

HRM -> UI: confirms the data
activate UI

UI -> CTRL : create collaborator
deactivate UI
activate CTRL

ref over CTRL
Get Collaborator Repository
end ref



CTRL -> CLBREP : createCLB(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType[], documentCode, admissionDate, job)
deactivate CTRL

activate CLBREP

ref over CLBREP
Register a Collaborator
end ref




CLBREP --> CTRL : collaborator
deactivate CLBREP

activate CTRL



CTRL --> UI : success
deactivate CTRL
activate UI
UI --> HRM : shows success message (collaborator created successfully)
deactivate UI
deactivate HRM
@enduml
