@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterCollaboratorController" as CTRL
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant ":Collaborator" as CLB

autonumber 38

group Pin Job

CTRL ->CLBREP : assignJob(job)
deactivate CTRL
activate CLBREP

CLBREP -> CLB : assignJob(job)
deactivate CLBREP
activate CLB
CLB -> CLB : setJob(job)
activate CLB
CLB --> CLB
deactivate CLB
end
CLB --> CLBREP : collaborator
deactivate CLB
activate CLBREP

@enduml