@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US013

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : wants to calculate the minimum cost tree
    activate System

        System --> Employee : asks for a file
    deactivate System

    Employee -> System : uploads the file
    activate System

        System --> Employee : operation success
    deactivate System

@enduml