@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US026

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to assign vehicles to an entry in the Agenda
    activate System

        System --> GSM : shows the entries in the agenda and asks to select one
    deactivate System

    GSM -> System : select the entry

    activate System

        System --> GSM : shows vehicles and asks to select one or more
    deactivate System

    GSM -> System : selects vehicles
    activate System

        System --> GSM :  displays success message (Vehicles assigned successfully)
    deactivate System

@enduml