@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US006

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : Request to add a new task in the Agenda
    activate System

        System --> GSM : shows the To-do List and requests to select a task
    deactivate System

    GSM -> System : selects a task

    activate System

        System --> GSM : requests a starting date for the selected task
    deactivate System

    GSM -> System : types date

    activate System

        System --> GSM : shows all data and requests confirmation
    deactivate System

    GSM -> System : confirms data
    activate System

        System --> GSM : displays success message (Task added to the Agenda successfully)
    deactivate System

@enduml