@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber


actor "QAM" as QAM
participant ":RunTestsUI" as UI
participant ":RunTestsController" as CTRL
participant ":GraphTest" as Test
activate QAM

        QAM -> UI : asks to run a test

        activate UI


            UI -> CTRL** : create
            activate CTRL

                CTRL -> Test : runs
                deactivate CTRL
                activate Test

                    Test -> RunGraphWP: send initial values
                    deactivate Test
                activate RunGraphWP

                    RunGraphWP -> RunGraphWP: runCalculus()
                RunGraphWP --> Test : results
                deactivate RunGraphWP
                activate Test

                Test -> Test : compareResults()

                Test --> CTRL : test results
                deactivate  Test

                activate CTRL
            deactivate Test

            CTRL --> UI : test results

        deactivate CTRL

    UI --> QAM : Displays passed or failed tests
    deactivate UI
deactivate QAM



@enduml