@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction


hide circle
hide methods


class Entry
 {
    title
    description
    duration
    urgencyStatus
}

@enduml