@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction


hide circle
hide methods


class Taskçç
 {
vin
vehiclePlate
tareWeight
grossWeight
currentKm
registrationDate
acquisitionDate
maintenanceFrequency
type
}

class Brand {
    designation
}

class Model {
    designation
}

Vehicle "1..*" - "1" Brand : has >
Model "1..*" -"1" Brand: has <
@enduml