@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US008

autonumber

actor "VFM" as VFM
participant ":System" as System

activate VFM

        VFM -> System : requests to list vehicles needing checkup
        activate System

            System --> VFM : shows list of vehicles needing checkup
        deactivate System

@enduml