@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model -- US005

class Skill {
  - name
  - description (optional)
}

class Collaborators {
  - name
  - date of birth
  - date of employment
  - address
  - phone number
  - email
  - id
  - identification document
  + hasSkills: Set<Skill>
}
class HRM{
}
class Team {
  - name
  - members: Set<Collaborators>
}

class TeamGenerator {
  - id
  - requiredSkills: Set<Skill>
  - numberOfCollaborators: int
  - suggestedTeam: Team (optional)
  + generateTeam(skills: Set<Skill>, numberOfCollaborators: int): TeamGenerator
}

Collaborators "0..*" -"*" Skill: possesses >
Team "1" -- "*" Collaborators: consists of >
TeamGenerator "0..1" --> "1" HRM: proposes >
HRM"0..*"-->"1" Team: accept >
@enduml
