@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model -- US005

class Team {
  - name
  - members: Set<Collaborates>
}

class TeamProposal {
  - id
  - requiredSkills: Set<Skill>
  - numberOfCollaborators: int
}

class TeamModify{
  - TeamProposal
  - Set <collaborates>
}


HRM "0...1" --> "1" Team: confirm propose >

HRM "1" --> "0...1" TeamProposal : receives proposals <
HRM --> TeamProposal: reject >
HRM --> TeamModify:  modify >
TeamModify --> Team: create a team >








@enduml
