@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'title System Sequence Diagram (SSD) - US006

autonumber

participant ":CancelAgendaEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:EntryRepository" as EntryRepo

autonumber 2

activate CTRL

 -> CTRL: create

    group Get Entry List

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> EntryRepo : getEntryRepository()
            activate EntryRepo

                EntryRepo --> CTRL : entryRepository
            deactivate EntryRepo

            CTRL -> EntryRepo :getEntryList()
            activate EntryRepo

            EntryRepo --> CTRL : entryList
            deactivate EntryRepo
    end

 <-- CTRL: entry List
deactivate CTRL


@enduml