@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":Agenda" as Agenda

autonumber 13

-> Agenda : cancelTask(entry)

activate Agenda
    group Cancel a Entry in Agenda

      Agenda -> Agenda : updateEntryStatus(entry, CANCELLED)

    end

<-- Agenda : success
deactivate Agenda


@enduml