@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'title System Sequence Diagram (SSD) - US006

autonumber

participant "GSM" as GSM
participant ":CancelAgendaEntrykUI" as UI
participant ":CancelAgendaEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:EntryRepository" as EntryRepo
participant ":Agenda" as Agenda
participant ":TeamRepository" as EntryRepo
participant ":NotificationService" as NotificationService

activate GSM
    GSM -> UI : requests to cancel an agenda entry
    activate UI

       UI -> CTRL : create
       deactivate UI
       activate CTRL

       ref over CTRL

          Get Entry List

       end ref

           CTRL --> UI : entry List
       deactivate CTRL
       activate UI

        UI -> GSM : shows the list of agenda entry and requests to select
    deactivate UI

    GSM -> UI : selects an agenda entry
    activate UI

        UI -> CTRL : submit cancellation request
        deactivate UI
        activate CTRL

            CTRL -> Agenda : cancelEntry(entry)
            deactivate CTRL
            activate Agenda

        ref over Agenda
            Cancel a Entry in Agenda

        end ref
                Agenda --> CTRL :
            deactivate Agenda
            activate CTRL

            CTRL -> EntryRepo : notifyTeam(entry)
            deactivate CTRL
            activate EntryRepo

                EntryRepo -> NotificationService : sendNotification(team)
                deactivate EntryRepo
                activate NotificationService

                    NotificationService --> EntryRepo : success
                deactivate NotificationService
                activate EntryRepo

            EntryRepo --> CTRL : success
            deactivate EntryRepo
            activate CTRL

            CTRL --> UI : success
        deactivate CTRL
        activate UI

        UI --> GSM : displays success message (Entry cancelled successfully)
    deactivate UI
@enduml
