@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":TeamRepository" as TeamRepo
participant ":NotificationService" as NotificationService


autonumber 16
 -> TeamRepo : notifyTeam(task)

activate TeamRepo
    group Notify Team

    TeamRepo -> NotificationService : sendNotification(team)
    deactivate TeamRepo
    activate NotificationService

    NotificationService --> TeamRepo : success
    deactivate NotificationService
    activate TeamRepo

    end

 <-- TeamRepo: success
deactivate TeamRepo


@enduml