@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US003

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to create a new collaborator with a job and fundamental characteristics
    activate System
loop until HRM confirms requests data
        System --> HRM : requests data (collaborator information, job, job skill(s))
    deactivate System

    HRM -> System : types requested data
    activate System

        System --> HRM : shows all data and requests confirmation
    deactivate System
end
    HRM -> System : confirms data
    activate System

        System --> HRM : displays operation success
    deactivate System

@enduml