@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US011

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : wants to create the statistic
    activate System

        System --> GSM : asks to upload the file
    deactivate System
    GSM -> System : uploads the file
    activate System

        System --> GSM : show the statistics
    deactivate System
@enduml
