@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "vehicle\n:Vehicle" as VEI

autonumber 15
 -> VEI: registerVehicle(VIN, Brand, Model, Type, Vehicle Plate, Tare Weight, \nGross Weight, Current Km, Registration date Acquisition Date, Maintenance Frequency)

activate VEI
    group Register Vehicle

        VEI -> VEI: validateVehicle(vehicle))
        activate VEI

        VEI --> VEI
        deactivate VEI

    end

    <-- VEI : vehicle
deactivate VEI


@enduml