@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register Vehicle (US006)

autonumber

actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant "organization\n:Organization" as ORG

activate VFM

    VFM -> UI : requests to register a vehicle
    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getVehicleData()
        ref over CTRL
            Get Vehicle Data

        end ref

        activate CTRL

            CTRL --> UI : vehicleData (Brand, Model, Type, Tare Weight, Gross Weight, Current Km, Register Date, Acquisition Date, and Maintenance/Check-up Frequency (in km))
        deactivate CTRL

        UI --> VFM : displays vehicle data form
    deactivate UI

    VFM -> UI : provides vehicle data
    activate UI

        UI --> VFM : confirms data
    deactivate UI

    VFM -> CTRL : confirms data
    activate CTRL

        CTRL -> ORG: createVehicle(vehicleData)
        activate ORG

            ref over ORG
                Create Vehicle

            end

            ORG --> CTRL : vehicleInfo
        deactivate ORG

        CTRL --> VFM : shows vehicle registration information
    deactivate CTRL

@enduml
