@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BrandRepository
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle\n:Vehicle" as VEI

activate VFM

    VFM -> UI : requests to register a vehicle
    activate UI

        UI -> CTRL** : create

        UI --> VFM : requests vehicle data (VIN, Vehicle Platte, Tare Weight, Gross Weight,\n Current Km, Acquisition Date, Maintenance Frequency)
        deactivate UI

    VFM -> UI : types vehicle data
    activate UI

        UI -> CTRL : submit vehicle data
        deactivate UI
        activate CTRL

            CTRL -> RepositorySingleton: getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT: getVehicleRepository
            activate PLAT

            PLAT --> CTRL: VehicleRepository
            deactivate PLAT

            CTRL -> VehicleRepository : validateVehicleData(VIN)
            deactivate CTRL
            activate VehicleRepository

            VehicleRepository -> VehicleRepository: validateVehicleData(VIN)
            activate VehicleRepository

            VehicleRepository --> VehicleRepository
            deactivate VehicleRepository

            VehicleRepository --> CTRL : vehicleData
            activate CTRL
            deactivate VehicleRepository



            ref over CTRL
                                            Get brand List

                                        end ref

            CTRL --> UI: brandList
            deactivate CTRL
            activate UI



    UI --> VFM : show brand list and request to select brand
    deactivate UI

    VFM -> UI : select vehicle brand
    activate UI

    UI -> CTRL : getModel()
    deactivate UI
    activate CTRL

        ref over CTRL
                                            Get model List

                                        end ref



    CTRL --> UI: modelList
    deactivate CTRL
    activate UI


    UI --> VFM : shows vehicle modelLis
    deactivate UI



    VFM -> UI : select vehicle brand
    activate UI

        UI -> CTRL : registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
        deactivate UI
        activate CTRL

            |||
            CTRL -> VehicleRepository : registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
            deactivate CTRL
            activate VehicleRepository

                VehicleRepository -> VEI **: registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
                deactivate VehicleRepository
                activate VEI

                        ref over VEI
                                                                    Register Vehicle

                                                                end ref


                 VEI --> VehicleRepository: vehicle
                                deactivate VEI

                activate VehicleRepository

            VehicleRepository --> CTRL: vehicle
            deactivate VehicleRepository
            activate CTRL

            CTRL --> UI: vehicle
            deactivate CTRL

activate UI

        UI --> VFM : shows success message
    deactivate UI

deactivate VFM

@enduml
