@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterVehicleController" as CTRL
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BrandRepository

autonumber 18
-> CTRL : registerVehicle(VIN, Brand, Model, Vehicle Platte,\nTare Weight, Gross Weight, Current Km, Acquisition Date,\nMaintenance Frequency)

activate CTRL
    group Get Model by Brand

        CTRL -> CTRL : getModelByBrand(brand)
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getBrandRepository()
        activate PLAT

        PLAT --> CTRL : BrandRepository
        deactivate PLAT

        CTRL -> BrandRepository : getModelByBrand(brand)
        activate BrandRepository

        BrandRepository --> CTRL : modelList
        deactivate BrandRepository

        CTRL --> CTRL : modelList
        deactivate CTRL

    end
    <-- CTRL : model list
deactivate CTRL


@enduml