@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam line type polyline



class VFM {
}

class Vehicle {
    - vin
    - vehiclePlate
    - tareWeight
    - grossWeight
    - currentKm
    - acquisitionDate
    - maintenanceFrequency
    - type

    + Vehicle(vin, vehiclePlate, tareWeight, grossWeight,currentKm, acquisitionDate, maintenanceFrequency, type)
}

class Brand {
    - model

    + Brand(model)
}

class VehicleRepository {
    + registerVehicle(vin, brand, model, vehiclePlate, tareWeight,grossWeight, currentKm, acquisitionDate, maintenanceFrequency)
    + validateVIN(vin)
}

class BrandRepository {
    + getBrands()
    + getModelByBrand(brand)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getBrandRepository()
    + getVehicleRepository()
}

class RegisterVehicleController {
    + submitVehicleData(vin, vehiclePlate, tareWeight, grossWeight,\ncurrentKm, acquisitionDate, maintenanceFrequency)
    + getBrand()
    + registerVehicle(vin, brand, model, vehiclePlate, tareWeight,\ngrossWeight, currentKm, acquisitionDate, maintenanceFrequency)
}

class RegisterVehicleUI {
}

VFM -> RegisterVehicleUI
Repositories -> Repositories : instance

RegisterVehicleUI .> RegisterVehicleController

RegisterVehicleController .> Repositories : repositories

Repositories -> "1" BrandRepository

RegisterVehicleController ..> Brand
RegisterVehicleController ..> VehicleRepository : vehicleRepository
RegisterVehicleController ..> BrandRepository : brandRepository

Repositories --> "1" VehicleRepository

VehicleRepository --> "*" Vehicle

RegisterVehicleController ..> "1" Brand : brand

Vehicle --> "1" Brand : brand

@enduml
