@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BrandRepository
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle\n:Vehicle" as VEI

activate VFM

    VFM -> UI : requests to register a vehicle
    activate UI

        UI -> CTRL** : create

        UI --> VFM : requests vehicle data (VIN, Vehicle Platte, Tare Weight, Gross Weight,\n Current Km, Acquisition Date, Maintenance Frequency)

    VFM -> UI : types vehicle data

        UI -> CTRL : submit vehicle data
        activate CTRL

            CTRL -> RepositorySingleton: getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT: getVehicleRepository
            activate PLAT

            PLAT --> CTRL: VehicleRepository
            deactivate PLAT

            CTRL -> VehicleRepository : validateVehicleData(VIN)
            activate VehicleRepository

            VehicleRepository -> VehicleRepository: validateVehicleData(VIN)
            activate VehicleRepository

            VehicleRepository --> VehicleRepository
            deactivate VehicleRepository



            VehicleRepository --> CTRL : vehicleData
            deactivate VehicleRepository

        CTRL --> UI : keep vehicle data
        deactivate CTRL

        UI -> CTRL : getBrand()
        activate CTRL

            ref over CTRL
                                            Get brand List

                                        end ref

            CTRL --> UI: brandList
            deactivate CTRL



    UI --> VFM : show brand list and request to select brand

    VFM -> UI : select vehicle brand

    UI -> CTRL : getModel()
    activate CTRL

        ref over CTRL
                                            Get model List

                                        end ref



    CTRL --> UI: modelList
    deactivate CTRL


        UI --> VFM : shows vehicle modelList

    VFM -> UI : select vehicle brand

        UI -> CTRL : registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
        activate CTRL

            |||
            CTRL -> VehicleRepository : registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
            activate VehicleRepository

                VehicleRepository -> VEI **: registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
                activate VEI

                        ref over VEI
                                                                    Register Vehicle

                                                                end ref




                VEI --> VehicleRepository: vehicle
                deactivate VEI

            VehicleRepository --> CTRL: vehicle
            deactivate VehicleRepository

            CTRL --> UI: vehicle
deactivate CTRL
        UI --> VFM : shows success message
    deactivate UI

deactivate VFM

@enduml
