@startuml
skinparam shadowing false
skinparam line type polyline

'left to right direction

    class RegisterVehicleUI {
    }

    class RegisterVehicleController {
        - vehicleRepository : VehicleRepository
        + registerVehicle(VIN: String, brand: String, model: String, type: String, vehiclePlate: String, \ntareWeight: double, grossWeight: double, currentKm: double, acquisitionDate: Date, maintenanceFrequency: int) : boolean
        + getVehicleRepository() : VehicleRepository
    }

    class Repositories {
        - vehicleRepository : VehicleRepository
        + getInstance() : Repositories
        + getVehicleRepository() : VehicleRepository
    }

    class VehicleRepository {
        + verifyExistingVehicle(VIN: String, VehiclePlate: String) : boolean
        + addVehicle(vehicle: Vehicle) : boolean
    }

    class Vehicle {
        - VIN : String
        - brand : String
        - model : String
        - type : String
        - vehiclePlate : String
        - tareWeight : double
        - grossWeight : double
        - currentKm : double
        - acquisitionDate : Date
        - maintenanceFrequency : int

        + validateVehicle(vehicle: Vehicle) : boolean
        + Vehicle(VIN, Brand, Model, Type, Vehicle Plate, Tare Weight, \nGross Weight, Current Km, Acquisition Date, Maintenance Frequency)
    }

RegisterVehicleUI ..> RegisterVehicleController
RegisterVehicleController ..> Repositories: repositories
Repositories --> Repositories: instance
RegisterVehicleController ..> VehicleRepository: vehicleRepository
Repositories --> "1"VehicleRepository: vehicleRepository
VehicleRepository "1"-->"*" Vehicle: vehicle

@enduml
