@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BrandRepository
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "vehicle\n:Vehicle" as VEI

activate VFM

    VFM -> UI : requests to register a vehicle
    activate UI

        UI -> CTRL** : create

        UI --> VFM : requests vehicle data (VIN, Vehicle Platte, Tare Weight, Gross Weight,\n Current Km, Acquisition Date, Maintenance Frequency)

    VFM -> UI : types vehicle data

        UI -> CTRL : submit vehicle data
        activate CTRL

            CTRL -> VehicleRepository : validateVehicleData(VIN)
            activate VehicleRepository

            VehicleRepository -> VehicleRepository: validateVehicleData(VIN)
            activate VehicleRepository

            VehicleRepository -> VehicleRepository
            deactivate VehicleRepository



            VehicleRepository -> CTRL : vehicleData
            deactivate VehicleRepository

        CTRL -> UI : keep vehicle data
        deactivate CTRL

        UI -> CTRL : getBrand()
        activate CTRL

            CTRL -> CTRL : getBrand()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getBrandRepository()
                activate PLAT

                PLAT --> CTRL : BrandRepository
                deactivate PLAT

                CTRL -> BrandRepository : getBrandList(brand))
                activate BrandRepository

                BrandRepository --> CTRL : brandList
                deactivate BrandRepository

                CTRL --> CTRL : brandList
                deactivate CTRL

            CTRL -> UI: brandList
            deactivate CTRL



    UI -> VFM : show brand list and request to select brand
    deactivate UI

    VFM -> UI : select vehicle brand
    activate UI

    UI -> CTRL : getModel()
    activate CTRL

        CTRL -> CTRL : getModelByBrand(brand)
                    activate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                        activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                        CTRL -> PLAT : getBrandRepository()
                        activate PLAT

                        PLAT --> CTRL : BrandRepository
                        deactivate PLAT

                        CTRL -> BrandRepository : getModelByBrand(brand)
                        activate BrandRepository

                        BrandRepository --> CTRL : modelList
                        deactivate BrandRepository

                    CTRL --> CTRL : modelList
                    deactivate CTRL

        CTRL -> UI: modelList
        deactivate CTRL


        UI -> VFM : shows vehicle modelList
    deactivate UI

    VFM -> UI : select vehicle brand
    activate UI

        UI -> CTRL : registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
        activate CTRL

            |||
            CTRL -> VehicleRepository : registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
            activate VehicleRepository

                VehicleRepository -> VEI **: registerVehicle(VIN, Brand, Model, \nVehicle Platte, Tare Weight, Gross Weight, \nCurrent Km, Acquisition Date, Maintenance Frequency)
                activate VEI

                    VEI -> VEI: addVehicle (vehicle)
                    activate VEI

                    VEI -> VEI: validateVehicle(vehicle))
                    activate VEI

                    VEI --> VEI
                    deactivate VEI

                    VEI --> VEI
                    deactivate VEI

                VEI -> VehicleRepository: vehicle
                deactivate VEI

            VehicleRepository -> CTRL: vehicle
            deactivate VehicleRepository

            CTRL -> UI: vehicle

        UI --> VFM : shows success message
    deactivate UI

deactivate VFM

@enduml
