@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterVehicleController" as CTRL
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BrandRepository

autonumber 18
-> CTRL : registerVehicle(VIN, Brand, Model, Vehicle Platte, Tare Weight, Gross Weight, Current Km, Acquisition Date, Maintenance Frequency)

autonumber 18.1
activate CTRL
    group Get Model by Brand

CTRL -> PLAT : getModel()
            CTRL -> CTRL : getModelByBrand(brand)
                                activate CTRL

                                    CTRL -> PLAT : getInstance()
                                    activate PLAT

                                    PLAT --> CTRL: repositories
                                    deactivate PLAT

                                    CTRL -> PLAT : getBrandRepository()
                                    activate PLAT

                                    PLAT -> CTRL : BrandRepository
                                    deactivate PLAT

                                    CTRL -> BrandRepository : getModelByBrand(brand)
                                    activate BrandRepository

                                    BrandRepository --> CTRL : modelList
                                    deactivate BrandRepository

                                CTRL --> CTRL : modelList
                                deactivate CTRL

    end
    deactivate CTRL

    autonumber 19
    <-- CTRL : model list
deactivate CTRL


@enduml