@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BrandRepository
autonumber 14

 -> CTRL : getBrand()
autonumber 14.1

activate CTRL

    group Get Brand List

            CTRL -> RepositorySingleton : getInstance()
                            activate RepositorySingleton

                            RepositorySingleton --> CTRL: repositories
                            deactivate RepositorySingleton

                            CTRL -> PLAT : getBrandRepository()
                            activate PLAT

                            PLAT -> CTRL : BrandRepository
                            deactivate PLAT

                            CTRL -> BrandRepository : getBrandList(brand))
                            activate BrandRepository

                            BrandRepository --> CTRL : brandList
                            deactivate BrandRepository

                            CTRL --> CTRL : brandList
                            deactivate CTRL

    end
    autonumber 15
    <-- CTRL  : brandList
deactivate CTRL


@enduml