@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register Vehicle (US006)

autonumber

'hide footbox
actor "Vehicle and Equipment Fleet Manager (VFM)" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "vehicle\n:Vehicle" as VEICULO

activate VFM

    VFM -> UI : requests to register a vehicle
    activate UI

                UI -> CTRL** : create

        UI -> VFM : requests vehicle data (VIN, Vehicle Platte, Tare Weight, Gross Weight, Current Km, Acquisition Date, Maintenance Frequency)
    deactivate UI

    VFM -> UI : types vehicle data
    activate UI


        UI -> CTRL : submitVehicleDetails(VIN, Vehicle Platte, Tare Weight, Gross Weight, Current Km, Acquisition Date, Maintenance Frequency)
        activate CTRL



            CTRL -> CTRL : validateVehicleData(Vin)
                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getVehicleRepository()
                activate PLAT

                    PLAT --> CTRL: vehicleRepository
                deactivate PLAT

                CTRL -> VehicleRepository : saveVehicle(vehicleData)
                activate VehicleRepository

                    VehicleRepository --> CTRL : vehicleInfo
                deactivate VehicleRepository

                CTRL -> UI: displaySuccessMessage(vehicleInfo)
                CTRL --> UI: displayErrorMessage(validationErrors)

        deactivate CTRL

        UI --> VFM : shows success/error message
    deactivate UI

deactivate VFM

@enduml
