@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "vehicleRepository:\nVehicleRepository" as VehicleRepository

autonumber 8
-> VehicleRepository : verifyExistedVehicle(VIN, Vehicle Platte)

activate VehicleRepository
    group Verify Vehicle Data
    autonumber 8.1

        VehicleRepository -> VehicleRepository: verifyExistedVehicle(VIN, Vehicle Plate)
        activate VehicleRepository

        VehicleRepository --> VehicleRepository
        deactivate VehicleRepository

    end
deactivate VehicleRepository


@enduml