@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Global Use Case Diagram

left to right direction

rectangle "System User" as actors {
    actor HRM
    actor VFM
    actor GSM
    actor QAM
}

rectangle "Use Cases" as usecases{
    usecase "UC001 - Register a Skill" as UC001
    HRM --> UC001
}

rectangle "Use Cases" as usecases{
    usecase "UC002 - Register a Job" as UC002
    HRM --> UC002
}

rectangle "Use Cases" as usecases{
    usecase "UC003 - Register a collaborator with a job\n and fundamental characteristics." as UC003
    HRM --> UC003
}

rectangle "Use Cases" as usecases{
    usecase "UC004 - Assign skills to a collaborator" as UC004
    HRM --> UC004
}

rectangle "Use Cases" as usecases{
    usecase "UC005 - Generate a team" as UC005
    HRM --> UC005
}

rectangle "Use Cases" as usecases{
    usecase "UC006 - Register a vehicle" as UC006
    VFM --> UC006
}

rectangle "Use Cases" as usecases{
    usecase "UC007 - Register a Vehicle check-up" as UC007
    VFM --> UC007
}

rectangle "Use Cases" as usecases{
    usecase "UC008 - List Vehicles Needing Check-up" as UC008
    VFM --> UC008
}

rectangle "Use Cases" as usecases{
    usecase "UC009 - See the exact costs referring to \nwater consumption of specific green spaces" as UC009
    GSM --> UC009
}

rectangle "Use Cases" as usecases{
    usecase "UC010 - See in a pie chart which piece(s) \nof equipment is/are used in each day" as UC010
    GSM --> UC010
}
rectangle "Use Cases" as usecases{
    usecase "UC011 - Collect data from the user portal" as UC011
    GSM --> UC011
}
rectangle "Use Cases" as usecases{
    usecase "UC012 - I want to import a .csv file containing routes" as UC012
    GSM --> UC012
}
rectangle "Use Cases" as usecases{
    usecase "UC013 - Apply an algorithm that returns the \nroutes to be opened, with minimum cost" as UC013
    GSM --> UC013
}
rectangle "Use Cases" as usecases{
    usecase "UC014 - Run tests for inputs of variable size, to observe \nthe asymptotic behavior of the execution time of the US13" as UC014
    QAM --> UC014
}
@enduml
