@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Global Use Case Diagram

left to right direction

rectangle "System User" as actors {
    actor HRM
    actor VFM
    actor GSM
    actor QAM
}

rectangle "Use Cases" as usecases{
    usecase "US001 - Register a Skill" as US001
    HRM --> US001
}

rectangle "Use Cases" as usecases{
    usecase "US002 - Register a Job" as US002
    HRM --> US002
}

rectangle "Use Cases" as usecases{
    usecase "US003 - Register a collaborator with a job\n and fundamental characteristics." as US003
    HRM --> US003
}

rectangle "Use Cases" as usecases{
    usecase "US004 - Assign skills to a collaborator" as US004
    HRM --> US004
}

rectangle "Use Cases" as usecases{
    usecase "US005 - Generate a team" as US005
    HRM --> US005
}

rectangle "Use Cases" as usecases{
    usecase "US006 - Register a vehicle" as US006
    VFM --> US006
}

rectangle "Use Cases" as usecases{
    usecase "US007 - Register a Vehicle check-up" as US007
    VFM --> US007
}

rectangle "Use Cases" as usecases{
    usecase "US008 - List Vehicles Needing Check-up" as US008
    VFM --> US008
}

rectangle "Use Cases" as usecases{
    usecase "US009 - Know the exact costs referring to \nwater consumption of specific green spaces" as US009
    GSM --> US009
}

rectangle "Use Cases" as usecases{
    usecase "US010 - Know in a pie chart which piece(s) \nof equipment is/are used in each day" as US010
    GSM --> US010
}
rectangle "Use Cases" as usecases{
    usecase "US011 - Collect data from the user portal" as US011
    GSM --> US011
}
rectangle "Use Cases" as usecases{
    usecase "US012 - Import a .csv file containing routes" as US012
    GSM --> US012
}
rectangle "Use Cases" as usecases{
    usecase "US013 - Apply an algorithm that returns the \nroutes to be opened, with minimum cost" as US013
    GSM --> US013
}
rectangle "Use Cases" as usecases{
    usecase "US014 - Run tests for inputs of variable size, to observe \nthe asymptotic behavior of the execution time of the US13" as US014
    QAM --> US014
}
@enduml
