@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant ":AnalyseParkWaterConsumptionUI" as UI
participant ":AnalyseParkWaterConsumptionController" as CTRL

activate GSM
GSM -> UI : wants to analyze water consumption costs
activate UI
UI -> CTRL** : creates
UI --> GSM : asks to upload the file (water_consumption.csv)
GSM -> UI : gives the file path (uploads the file)
UI -> CTRL : sends the file
deactivate UI
activate CTRL
CTRL -> CTRL : checks for formatting errors
activate CTRL
CTRL -->CTRL
deactivate CTRL
CTRL -> CTRL : runs the statistical analysis
CTRL --> UI : results
deactivate CTRL
activate UI
UI --> GSM : shows the results window
deactivate UI
deactivate GSM
@enduml