@startuml
skinparam shadowing false
skinparam line type polyline

'left to right direction

class Maintenance {
    - date: LocalDate
    - vehiclePlate: String
    - km: int

    + Maintenance( vehiclePlate: String, date : LocalDate, kilometers: int)
    + getDate() : LocalDate
    + getKm() : int
    + getVehiclePlate() : String
}


class MaintenanceRepository {
    + createMaintenance(String plate, Date date, int currentKm) : void
}

class Repositories {
-maintenanceRepository : MaintenanceRepository
        - instance : Repositories
        - Repositories()
    + getInstance() : Repositories
    + getMaintenanceRepository()
}

class RegisterMaintenanceController {
    + RegisterMaintenanceController()
    + getMaintenanceRepository()
}

class RegisterMaintenanceUI {
}

Repositories -> Repositories : instance

RegisterMaintenanceUI .> RegisterMaintenanceController

RegisterMaintenanceController .> Repositories

RegisterMaintenanceController ..> MaintenanceRepository

Repositories -> "1" MaintenanceRepository

MaintenanceRepository "1" -> "*" Maintenance


RegisterMaintenanceController ..> Maintenance


@enduml
