@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class FM {
}

class Vehicle {
vin
vehiclePlate
brand
model
tareWeight
grossWeight
currentKm
acquisitionDate
maintenanceFrequency
type
}
\
FM "1" - "0..*" Vehicle : creates  >
@enduml