@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US012

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : requests to import a .csv file
    activate System


        System --> GSM : displays confirmation message
    deactivate System

@enduml
