@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US029

autonumber

actor "CLB" as CLB
participant ":System" as System

activate CLB

    CLB -> System : asks to record a complete entry
    activate System

        System --> CLB : shows the list of the entry assign to the collaborator and requests to select the one to record
    deactivate System

    CLB -> System : select an assign entry

    activate System

        System --> CLB : show entry and requests confirmation
    deactivate System

    CLB -> System : confirms data
    activate System

        System --> CLB :  displays a success message (Entry record as completed)
    deactivate System

@enduml