@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

class HRM {
}

class Job {
    title
    description
}

class Collaborator {
    Name
    Birthdate
    Address
    Contact
    Identification document
    Identification number
    Taxpayer number
}

' Relationships
HRM "*" -- "1..*" Collaborator : registers >
HRM -- "1" Job : assigns >
Job "*" -- "1..*" Collaborator : assigned to >

@enduml
