@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class HRM {
}

class Job {
    title
    description
}

class Collaborator {

}

class Person {
    name
    birthdate
    address
    contact

}

class IdentificationDocument{
  identificationNumber
  taxPayerNumber
}

' Relationships
HRM  -->  Person
Collaborator  -->  Person
Person  -->  IdentificationDocument
HRM "*" -- "1" Collaborator : registers >
HRM -- "1" Job : assigns >
Job "1" -- "1..*" Collaborator : to >

@enduml
