
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'title System Sequence Diagram (SSD) - US026

autonumber

actor "GSM" as GSM
participant ":AssignVehiclesUI" as UI
participant ":AssignVehiclesController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository\n:EntryRepository" as EntryRepo
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant ":AgendaEntryMapper" as AgendaEntryMapper
participant "agendaEntryDto\n:AgendaEntryDto" as AgendaEntryDto
participant "agendaEntry\n:AgendaEntry" as AgendaEntry

activate GSM

    GSM -> UI : asks to assign vehicles to an entry in the Agenda
    activate UI

        UI -> CTRL** : create
        deactivate UI
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL : repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getEntryRepository()
                    activate PLAT

                        PLAT --> CTRL : entryRepository
                    deactivate PLAT

                     deactivate CTRL

                deactivate UI

        UI -> CTRL: getAgendaEntryList(GSM)
                        activate UI
                        activate CTRL

                            CTRL -> EntryRepo: getAgendaEntryListByGSM(GSM)
                            deactivate CTRL
                            activate EntryRepo

                            loop

                            EntryRepo -> AgendaEntryMapper : toDto(agendaEntry)
                            activate AgendaEntryMapper

                                AgendaEntryMapper -> AgendaEntryDto** : create
                                activate AgendaEntryDto

                                AgendaEntryDto --> AgendaEntryMapper : agendaEntryDTO
                                deactivate AgendaEntryDto

                            AgendaEntryMapper --> EntryRepo : agendaEntryDTO
                            deactivate AgendaEntryMapper
                            end

                            EntryRepo --> CTRL : agendaEntryDtoList
                            deactivate EntryRepo
                            activate CTRL

                        CTRL --> UI : agendaEntryDtoList
                        deactivate CTRL
                        deactivate UI

        UI -> CTRL : getVehiclesList()
                activate UI
                activate CTRL

                CTRL -> VehicleRepository : getVehiclesList()
                activate VehicleRepository

                VehicleRepository -> CTRL : vehiclesList
                deactivate VehicleRepository

                CTRL -> UI : vehiclesList
                deactivate CTRL

    UI --> GSM : shows the entries in the agenda and asks to select one
        deactivate UI

    GSM -> UI : select the entry
    activate UI

    loop

    UI --> GSM : shows vehicles and asks to select one or more
    deactivate UI

    GSM -> UI: selects vehicles
    activate UI

    end loop

    UI --> GSM : shows all data and requests confirmation
    deactivate UI

    GSM -> UI: confirms
    activate UI

        UI -> CTRL : assignVehiclesToEntry(agendaEntryDto)
                        deactivate UI
                        activate CTRL


                            CTRL -> EntryRepo : updateAgendaEntryVehicles(agendaEntryDto, Vehicles[])
                            deactivate CTRL
                            activate EntryRepo

                            EntryRepo -> AgendaEntryMapper : toDomain(agendaEntryDto)
                            activate AgendaEntryMapper

                                AgendaEntryMapper -> AgendaEntry** : create
                                activate AgendaEntry

                                AgendaEntry --> AgendaEntryMapper : agendaEntry
                                deactivate AgendaEntry

                            AgendaEntryMapper --> EntryRepo : agendaEntry
                            deactivate AgendaEntryMapper

                                EntryRepo -> EntryRepo : updateEntryVehicles(agendaEntry, Vehicles[])

                            EntryRepo --> CTRL : success
                            deactivate EntryRepo
                            activate CTRL

        CTRL --> UI : success
        deactivate CTRL
        activate UI

    UI --> GSM : displays success message (Vehicles assigned successfully)
    deactivate UI

deactivate GSM

@enduml
