@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US001

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to create a new skill
    activate System

        System --> HRM : requests data (a description to the skill to be created)
    deactivate System

    HRM -> System : types requested data
    activate System

        System --> HRM : shows a error dialog (have a existing skill with the same name)
    deactivate System


@enduml