@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US005

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to create a new team
    activate System
loop until HRM confirms data requests

        System --> HRM : requests data (skills, maximum team size)
    deactivate System

    HRM -> System : selects requested data
    activate System

        System --> HRM : shows the proposal
    deactivate System
opt if HRM wants to modify team proposal
    HRM -> System : user want to modify the collaborator
    activate System

        System --> HRM : shows the collaborator to modify
    deactivate System

    HRM -> System : user change the collaborator
    activate System

    System --> HRM : system verifies and shows new team propose
    deactivate System
end
 HRM -> System : user confirms team proposal
     activate System
end
     System --> HRM : system create a new team
     deactivate System

@enduml